/**
 * Magento Enterprise Edition 2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.magento) {
      root.magento = {};
    }
    root.magento.Body109 = factory(root.magento.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Body109 model module.
   * @module model/Body109
   * @version 2.0
   */

  /**
   * Constructs a new <code>Body109</code>.
   * @alias module:model/Body109
   * @class
   * @param childSku {String} 
   */
  var exports = function(childSku) {
    var _this = this;

    _this['childSku'] = childSku;
  };

  /**
   * Constructs a <code>Body109</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Body109} obj Optional instance to populate.
   * @return {module:model/Body109} The populated <code>Body109</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('childSku')) {
        obj['childSku'] = ApiClient.convertToType(data['childSku'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} childSku
   */
  exports.prototype['childSku'] = undefined;



  return exports;
}));


