/**
 * Magento Enterprise Edition 2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.magento) {
      root.magento = {};
    }
    root.magento.Body105 = factory(root.magento.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Body105 model module.
   * @module model/Body105
   * @version 2.0
   */

  /**
   * Constructs a new <code>Body105</code>.
   * @alias module:model/Body105
   * @class
   * @param codes {Array.<String>} 
   */
  var exports = function(codes) {
    var _this = this;

    _this['codes'] = codes;

  };

  /**
   * Constructs a <code>Body105</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Body105} obj Optional instance to populate.
   * @return {module:model/Body105} The populated <code>Body105</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('codes')) {
        obj['codes'] = ApiClient.convertToType(data['codes'], ['String']);
      }
      if (data.hasOwnProperty('ignoreInvalidCoupons')) {
        obj['ignoreInvalidCoupons'] = ApiClient.convertToType(data['ignoreInvalidCoupons'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {Array.<String>} codes
   */
  exports.prototype['codes'] = undefined;
  /**
   * @member {Boolean} ignoreInvalidCoupons
   */
  exports.prototype['ignoreInvalidCoupons'] = undefined;



  return exports;
}));


