/**
 * Magento Enterprise Edition 2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GiftCardAccountDataGiftCardAccountInterface'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./GiftCardAccountDataGiftCardAccountInterface'));
  } else {
    // Browser globals (root is window)
    if (!root.magento) {
      root.magento = {};
    }
    root.magento.Body108 = factory(root.magento.ApiClient, root.magento.GiftCardAccountDataGiftCardAccountInterface);
  }
}(this, function(ApiClient, GiftCardAccountDataGiftCardAccountInterface) {
  'use strict';




  /**
   * The Body108 model module.
   * @module model/Body108
   * @version 2.0
   */

  /**
   * Constructs a new <code>Body108</code>.
   * @alias module:model/Body108
   * @class
   * @param giftCardAccountData {module:model/GiftCardAccountDataGiftCardAccountInterface} 
   */
  var exports = function(giftCardAccountData) {
    var _this = this;

    _this['giftCardAccountData'] = giftCardAccountData;
  };

  /**
   * Constructs a <code>Body108</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Body108} obj Optional instance to populate.
   * @return {module:model/Body108} The populated <code>Body108</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('giftCardAccountData')) {
        obj['giftCardAccountData'] = GiftCardAccountDataGiftCardAccountInterface.constructFromObject(data['giftCardAccountData']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/GiftCardAccountDataGiftCardAccountInterface} giftCardAccountData
   */
  exports.prototype['giftCardAccountData'] = undefined;



  return exports;
}));


