/**
 * Magento Enterprise Edition 2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DownloadableDataSampleInterface'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DownloadableDataSampleInterface'));
  } else {
    // Browser globals (root is window)
    if (!root.magento) {
      root.magento = {};
    }
    root.magento.Body81 = factory(root.magento.ApiClient, root.magento.DownloadableDataSampleInterface);
  }
}(this, function(ApiClient, DownloadableDataSampleInterface) {
  'use strict';




  /**
   * The Body81 model module.
   * @module model/Body81
   * @version 2.0
   */

  /**
   * Constructs a new <code>Body81</code>.
   * @alias module:model/Body81
   * @class
   * @param sample {module:model/DownloadableDataSampleInterface} 
   */
  var exports = function(sample) {
    var _this = this;

    _this['sample'] = sample;

  };

  /**
   * Constructs a <code>Body81</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Body81} obj Optional instance to populate.
   * @return {module:model/Body81} The populated <code>Body81</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('sample')) {
        obj['sample'] = DownloadableDataSampleInterface.constructFromObject(data['sample']);
      }
      if (data.hasOwnProperty('isGlobalScopeContent')) {
        obj['isGlobalScopeContent'] = ApiClient.convertToType(data['isGlobalScopeContent'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/DownloadableDataSampleInterface} sample
   */
  exports.prototype['sample'] = undefined;
  /**
   * @member {Boolean} isGlobalScopeContent
   */
  exports.prototype['isGlobalScopeContent'] = undefined;



  return exports;
}));


