/**
 * Magento Enterprise Edition 2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SalesRuleDataCouponInterface'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SalesRuleDataCouponInterface'));
  } else {
    // Browser globals (root is window)
    if (!root.magento) {
      root.magento = {};
    }
    root.magento.Body102 = factory(root.magento.ApiClient, root.magento.SalesRuleDataCouponInterface);
  }
}(this, function(ApiClient, SalesRuleDataCouponInterface) {
  'use strict';




  /**
   * The Body102 model module.
   * @module model/Body102
   * @version 2.0
   */

  /**
   * Constructs a new <code>Body102</code>.
   * @alias module:model/Body102
   * @class
   * @param coupon {module:model/SalesRuleDataCouponInterface} 
   */
  var exports = function(coupon) {
    var _this = this;

    _this['coupon'] = coupon;
  };

  /**
   * Constructs a <code>Body102</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Body102} obj Optional instance to populate.
   * @return {module:model/Body102} The populated <code>Body102</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('coupon')) {
        obj['coupon'] = SalesRuleDataCouponInterface.constructFromObject(data['coupon']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/SalesRuleDataCouponInterface} coupon
   */
  exports.prototype['coupon'] = undefined;



  return exports;
}));


