/**
 * Magento Enterprise Edition 2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CatalogDataProductTierPriceExtensionInterface'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CatalogDataProductTierPriceExtensionInterface'));
  } else {
    // Browser globals (root is window)
    if (!root.magento) {
      root.magento = {};
    }
    root.magento.CatalogDataProductTierPriceInterface = factory(root.magento.ApiClient, root.magento.CatalogDataProductTierPriceExtensionInterface);
  }
}(this, function(ApiClient, CatalogDataProductTierPriceExtensionInterface) {
  'use strict';




  /**
   * The CatalogDataProductTierPriceInterface model module.
   * @module model/CatalogDataProductTierPriceInterface
   * @version 2.0
   */

  /**
   * Constructs a new <code>CatalogDataProductTierPriceInterface</code>.
   * 
   * @alias module:model/CatalogDataProductTierPriceInterface
   * @class
   * @param customerGroupId {Number} Customer group id
   * @param qty {Number} Tier qty
   * @param value {Number} Price value
   */
  var exports = function(customerGroupId, qty, value) {
    var _this = this;

    _this['customerGroupId'] = customerGroupId;
    _this['qty'] = qty;
    _this['value'] = value;

  };

  /**
   * Constructs a <code>CatalogDataProductTierPriceInterface</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CatalogDataProductTierPriceInterface} obj Optional instance to populate.
   * @return {module:model/CatalogDataProductTierPriceInterface} The populated <code>CatalogDataProductTierPriceInterface</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('customerGroupId')) {
        obj['customerGroupId'] = ApiClient.convertToType(data['customerGroupId'], 'Number');
      }
      if (data.hasOwnProperty('qty')) {
        obj['qty'] = ApiClient.convertToType(data['qty'], 'Number');
      }
      if (data.hasOwnProperty('value')) {
        obj['value'] = ApiClient.convertToType(data['value'], 'Number');
      }
      if (data.hasOwnProperty('extensionAttributes')) {
        obj['extensionAttributes'] = CatalogDataProductTierPriceExtensionInterface.constructFromObject(data['extensionAttributes']);
      }
    }
    return obj;
  }

  /**
   * Customer group id
   * @member {Number} customerGroupId
   */
  exports.prototype['customerGroupId'] = undefined;
  /**
   * Tier qty
   * @member {Number} qty
   */
  exports.prototype['qty'] = undefined;
  /**
   * Price value
   * @member {Number} value
   */
  exports.prototype['value'] = undefined;
  /**
   * @member {module:model/CatalogDataProductTierPriceExtensionInterface} extensionAttributes
   */
  exports.prototype['extensionAttributes'] = undefined;



  return exports;
}));


