/**
 * Magento Enterprise Edition 2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.magento) {
      root.magento = {};
    }
    root.magento.CatalogDataProductCustomOptionValuesInterface = factory(root.magento.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CatalogDataProductCustomOptionValuesInterface model module.
   * @module model/CatalogDataProductCustomOptionValuesInterface
   * @version 2.0
   */

  /**
   * Constructs a new <code>CatalogDataProductCustomOptionValuesInterface</code>.
   * 
   * @alias module:model/CatalogDataProductCustomOptionValuesInterface
   * @class
   * @param title {String} Option title
   * @param sortOrder {Number} Sort order
   * @param price {Number} Price
   * @param priceType {String} Price type
   */
  var exports = function(title, sortOrder, price, priceType) {
    var _this = this;

    _this['title'] = title;
    _this['sortOrder'] = sortOrder;
    _this['price'] = price;
    _this['priceType'] = priceType;


  };

  /**
   * Constructs a <code>CatalogDataProductCustomOptionValuesInterface</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CatalogDataProductCustomOptionValuesInterface} obj Optional instance to populate.
   * @return {module:model/CatalogDataProductCustomOptionValuesInterface} The populated <code>CatalogDataProductCustomOptionValuesInterface</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('sortOrder')) {
        obj['sortOrder'] = ApiClient.convertToType(data['sortOrder'], 'Number');
      }
      if (data.hasOwnProperty('price')) {
        obj['price'] = ApiClient.convertToType(data['price'], 'Number');
      }
      if (data.hasOwnProperty('priceType')) {
        obj['priceType'] = ApiClient.convertToType(data['priceType'], 'String');
      }
      if (data.hasOwnProperty('sku')) {
        obj['sku'] = ApiClient.convertToType(data['sku'], 'String');
      }
      if (data.hasOwnProperty('optionTypeId')) {
        obj['optionTypeId'] = ApiClient.convertToType(data['optionTypeId'], 'Number');
      }
    }
    return obj;
  }

  /**
   * Option title
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * Sort order
   * @member {Number} sortOrder
   */
  exports.prototype['sortOrder'] = undefined;
  /**
   * Price
   * @member {Number} price
   */
  exports.prototype['price'] = undefined;
  /**
   * Price type
   * @member {String} priceType
   */
  exports.prototype['priceType'] = undefined;
  /**
   * Sku
   * @member {String} sku
   */
  exports.prototype['sku'] = undefined;
  /**
   * Option type id
   * @member {Number} optionTypeId
   */
  exports.prototype['optionTypeId'] = undefined;



  return exports;
}));


