/**
 * Magento Enterprise Edition 2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CatalogDataProductLinkAttributeExtensionInterface'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CatalogDataProductLinkAttributeExtensionInterface'));
  } else {
    // Browser globals (root is window)
    if (!root.magento) {
      root.magento = {};
    }
    root.magento.CatalogDataProductLinkAttributeInterface = factory(root.magento.ApiClient, root.magento.CatalogDataProductLinkAttributeExtensionInterface);
  }
}(this, function(ApiClient, CatalogDataProductLinkAttributeExtensionInterface) {
  'use strict';




  /**
   * The CatalogDataProductLinkAttributeInterface model module.
   * @module model/CatalogDataProductLinkAttributeInterface
   * @version 2.0
   */

  /**
   * Constructs a new <code>CatalogDataProductLinkAttributeInterface</code>.
   * 
   * @alias module:model/CatalogDataProductLinkAttributeInterface
   * @class
   * @param code {String} Attribute code
   * @param type {String} Attribute type
   */
  var exports = function(code, type) {
    var _this = this;

    _this['code'] = code;
    _this['type'] = type;

  };

  /**
   * Constructs a <code>CatalogDataProductLinkAttributeInterface</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CatalogDataProductLinkAttributeInterface} obj Optional instance to populate.
   * @return {module:model/CatalogDataProductLinkAttributeInterface} The populated <code>CatalogDataProductLinkAttributeInterface</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('code')) {
        obj['code'] = ApiClient.convertToType(data['code'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('extensionAttributes')) {
        obj['extensionAttributes'] = CatalogDataProductLinkAttributeExtensionInterface.constructFromObject(data['extensionAttributes']);
      }
    }
    return obj;
  }

  /**
   * Attribute code
   * @member {String} code
   */
  exports.prototype['code'] = undefined;
  /**
   * Attribute type
   * @member {String} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {module:model/CatalogDataProductLinkAttributeExtensionInterface} extensionAttributes
   */
  exports.prototype['extensionAttributes'] = undefined;



  return exports;
}));


