/**
 * Magento Enterprise Edition 2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CatalogDataProductLinkExtensionInterface'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CatalogDataProductLinkExtensionInterface'));
  } else {
    // Browser globals (root is window)
    if (!root.magento) {
      root.magento = {};
    }
    root.magento.CatalogDataProductLinkInterface = factory(root.magento.ApiClient, root.magento.CatalogDataProductLinkExtensionInterface);
  }
}(this, function(ApiClient, CatalogDataProductLinkExtensionInterface) {
  'use strict';




  /**
   * The CatalogDataProductLinkInterface model module.
   * @module model/CatalogDataProductLinkInterface
   * @version 2.0
   */

  /**
   * Constructs a new <code>CatalogDataProductLinkInterface</code>.
   * 
   * @alias module:model/CatalogDataProductLinkInterface
   * @class
   * @param sku {String} SKU
   * @param linkType {String} Link type
   * @param linkedProductSku {String} Linked product sku
   * @param linkedProductType {String} Linked product type (simple, virtual, etc)
   * @param position {Number} Linked item position
   */
  var exports = function(sku, linkType, linkedProductSku, linkedProductType, position) {
    var _this = this;

    _this['sku'] = sku;
    _this['linkType'] = linkType;
    _this['linkedProductSku'] = linkedProductSku;
    _this['linkedProductType'] = linkedProductType;
    _this['position'] = position;

  };

  /**
   * Constructs a <code>CatalogDataProductLinkInterface</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CatalogDataProductLinkInterface} obj Optional instance to populate.
   * @return {module:model/CatalogDataProductLinkInterface} The populated <code>CatalogDataProductLinkInterface</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('sku')) {
        obj['sku'] = ApiClient.convertToType(data['sku'], 'String');
      }
      if (data.hasOwnProperty('linkType')) {
        obj['linkType'] = ApiClient.convertToType(data['linkType'], 'String');
      }
      if (data.hasOwnProperty('linkedProductSku')) {
        obj['linkedProductSku'] = ApiClient.convertToType(data['linkedProductSku'], 'String');
      }
      if (data.hasOwnProperty('linkedProductType')) {
        obj['linkedProductType'] = ApiClient.convertToType(data['linkedProductType'], 'String');
      }
      if (data.hasOwnProperty('position')) {
        obj['position'] = ApiClient.convertToType(data['position'], 'Number');
      }
      if (data.hasOwnProperty('extensionAttributes')) {
        obj['extensionAttributes'] = CatalogDataProductLinkExtensionInterface.constructFromObject(data['extensionAttributes']);
      }
    }
    return obj;
  }

  /**
   * SKU
   * @member {String} sku
   */
  exports.prototype['sku'] = undefined;
  /**
   * Link type
   * @member {String} linkType
   */
  exports.prototype['linkType'] = undefined;
  /**
   * Linked product sku
   * @member {String} linkedProductSku
   */
  exports.prototype['linkedProductSku'] = undefined;
  /**
   * Linked product type (simple, virtual, etc)
   * @member {String} linkedProductType
   */
  exports.prototype['linkedProductType'] = undefined;
  /**
   * Linked item position
   * @member {Number} position
   */
  exports.prototype['position'] = undefined;
  /**
   * @member {module:model/CatalogDataProductLinkExtensionInterface} extensionAttributes
   */
  exports.prototype['extensionAttributes'] = undefined;



  return exports;
}));


