/**
 * Magento Enterprise Edition 2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CatalogDataProductAttributeMediaGalleryEntryInterface', 'model/CatalogDataProductCustomOptionInterface', 'model/CatalogDataProductExtensionInterface', 'model/CatalogDataProductLinkInterface', 'model/CatalogDataProductTierPriceInterface', 'model/FrameworkAttributeInterface'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CatalogDataProductAttributeMediaGalleryEntryInterface'), require('./CatalogDataProductCustomOptionInterface'), require('./CatalogDataProductExtensionInterface'), require('./CatalogDataProductLinkInterface'), require('./CatalogDataProductTierPriceInterface'), require('./FrameworkAttributeInterface'));
  } else {
    // Browser globals (root is window)
    if (!root.magento) {
      root.magento = {};
    }
    root.magento.CatalogDataProductInterface = factory(root.magento.ApiClient, root.magento.CatalogDataProductAttributeMediaGalleryEntryInterface, root.magento.CatalogDataProductCustomOptionInterface, root.magento.CatalogDataProductExtensionInterface, root.magento.CatalogDataProductLinkInterface, root.magento.CatalogDataProductTierPriceInterface, root.magento.FrameworkAttributeInterface);
  }
}(this, function(ApiClient, CatalogDataProductAttributeMediaGalleryEntryInterface, CatalogDataProductCustomOptionInterface, CatalogDataProductExtensionInterface, CatalogDataProductLinkInterface, CatalogDataProductTierPriceInterface, FrameworkAttributeInterface) {
  'use strict';




  /**
   * The CatalogDataProductInterface model module.
   * @module model/CatalogDataProductInterface
   * @version 2.0
   */

  /**
   * Constructs a new <code>CatalogDataProductInterface</code>.
   * 
   * @alias module:model/CatalogDataProductInterface
   * @class
   * @param sku {String} Sku
   */
  var exports = function(sku) {
    var _this = this;


    _this['sku'] = sku;















  };

  /**
   * Constructs a <code>CatalogDataProductInterface</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CatalogDataProductInterface} obj Optional instance to populate.
   * @return {module:model/CatalogDataProductInterface} The populated <code>CatalogDataProductInterface</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('sku')) {
        obj['sku'] = ApiClient.convertToType(data['sku'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('attributeSetId')) {
        obj['attributeSetId'] = ApiClient.convertToType(data['attributeSetId'], 'Number');
      }
      if (data.hasOwnProperty('price')) {
        obj['price'] = ApiClient.convertToType(data['price'], 'Number');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'Number');
      }
      if (data.hasOwnProperty('visibility')) {
        obj['visibility'] = ApiClient.convertToType(data['visibility'], 'Number');
      }
      if (data.hasOwnProperty('typeId')) {
        obj['typeId'] = ApiClient.convertToType(data['typeId'], 'String');
      }
      if (data.hasOwnProperty('createdAt')) {
        obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'String');
      }
      if (data.hasOwnProperty('updatedAt')) {
        obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'String');
      }
      if (data.hasOwnProperty('weight')) {
        obj['weight'] = ApiClient.convertToType(data['weight'], 'Number');
      }
      if (data.hasOwnProperty('extensionAttributes')) {
        obj['extensionAttributes'] = CatalogDataProductExtensionInterface.constructFromObject(data['extensionAttributes']);
      }
      if (data.hasOwnProperty('productLinks')) {
        obj['productLinks'] = ApiClient.convertToType(data['productLinks'], [CatalogDataProductLinkInterface]);
      }
      if (data.hasOwnProperty('options')) {
        obj['options'] = ApiClient.convertToType(data['options'], [CatalogDataProductCustomOptionInterface]);
      }
      if (data.hasOwnProperty('mediaGalleryEntries')) {
        obj['mediaGalleryEntries'] = ApiClient.convertToType(data['mediaGalleryEntries'], [CatalogDataProductAttributeMediaGalleryEntryInterface]);
      }
      if (data.hasOwnProperty('tierPrices')) {
        obj['tierPrices'] = ApiClient.convertToType(data['tierPrices'], [CatalogDataProductTierPriceInterface]);
      }
      if (data.hasOwnProperty('customAttributes')) {
        obj['customAttributes'] = ApiClient.convertToType(data['customAttributes'], [FrameworkAttributeInterface]);
      }
    }
    return obj;
  }

  /**
   * Id
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * Sku
   * @member {String} sku
   */
  exports.prototype['sku'] = undefined;
  /**
   * Name
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * Attribute set id
   * @member {Number} attributeSetId
   */
  exports.prototype['attributeSetId'] = undefined;
  /**
   * Price
   * @member {Number} price
   */
  exports.prototype['price'] = undefined;
  /**
   * Status
   * @member {Number} status
   */
  exports.prototype['status'] = undefined;
  /**
   * Visibility
   * @member {Number} visibility
   */
  exports.prototype['visibility'] = undefined;
  /**
   * Type id
   * @member {String} typeId
   */
  exports.prototype['typeId'] = undefined;
  /**
   * Created date
   * @member {String} createdAt
   */
  exports.prototype['createdAt'] = undefined;
  /**
   * Updated date
   * @member {String} updatedAt
   */
  exports.prototype['updatedAt'] = undefined;
  /**
   * Weight
   * @member {Number} weight
   */
  exports.prototype['weight'] = undefined;
  /**
   * @member {module:model/CatalogDataProductExtensionInterface} extensionAttributes
   */
  exports.prototype['extensionAttributes'] = undefined;
  /**
   * Product links info
   * @member {Array.<module:model/CatalogDataProductLinkInterface>} productLinks
   */
  exports.prototype['productLinks'] = undefined;
  /**
   * List of product options
   * @member {Array.<module:model/CatalogDataProductCustomOptionInterface>} options
   */
  exports.prototype['options'] = undefined;
  /**
   * Media gallery entries
   * @member {Array.<module:model/CatalogDataProductAttributeMediaGalleryEntryInterface>} mediaGalleryEntries
   */
  exports.prototype['mediaGalleryEntries'] = undefined;
  /**
   * List of product tier prices
   * @member {Array.<module:model/CatalogDataProductTierPriceInterface>} tierPrices
   */
  exports.prototype['tierPrices'] = undefined;
  /**
   * Custom attributes values.
   * @member {Array.<module:model/FrameworkAttributeInterface>} customAttributes
   */
  exports.prototype['customAttributes'] = undefined;



  return exports;
}));


