/**
 * Magento Enterprise Edition 2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CatalogDataCustomOptionExtensionInterface'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CatalogDataCustomOptionExtensionInterface'));
  } else {
    // Browser globals (root is window)
    if (!root.magento) {
      root.magento = {};
    }
    root.magento.CatalogDataCustomOptionInterface = factory(root.magento.ApiClient, root.magento.CatalogDataCustomOptionExtensionInterface);
  }
}(this, function(ApiClient, CatalogDataCustomOptionExtensionInterface) {
  'use strict';




  /**
   * The CatalogDataCustomOptionInterface model module.
   * @module model/CatalogDataCustomOptionInterface
   * @version 2.0
   */

  /**
   * Constructs a new <code>CatalogDataCustomOptionInterface</code>.
   * Interface CustomOptionInterface
   * @alias module:model/CatalogDataCustomOptionInterface
   * @class
   * @param optionId {String} Option id
   * @param optionValue {String} Option value
   */
  var exports = function(optionId, optionValue) {
    var _this = this;

    _this['optionId'] = optionId;
    _this['optionValue'] = optionValue;

  };

  /**
   * Constructs a <code>CatalogDataCustomOptionInterface</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CatalogDataCustomOptionInterface} obj Optional instance to populate.
   * @return {module:model/CatalogDataCustomOptionInterface} The populated <code>CatalogDataCustomOptionInterface</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('optionId')) {
        obj['optionId'] = ApiClient.convertToType(data['optionId'], 'String');
      }
      if (data.hasOwnProperty('optionValue')) {
        obj['optionValue'] = ApiClient.convertToType(data['optionValue'], 'String');
      }
      if (data.hasOwnProperty('extensionAttributes')) {
        obj['extensionAttributes'] = CatalogDataCustomOptionExtensionInterface.constructFromObject(data['extensionAttributes']);
      }
    }
    return obj;
  }

  /**
   * Option id
   * @member {String} optionId
   */
  exports.prototype['optionId'] = undefined;
  /**
   * Option value
   * @member {String} optionValue
   */
  exports.prototype['optionValue'] = undefined;
  /**
   * @member {module:model/CatalogDataCustomOptionExtensionInterface} extensionAttributes
   */
  exports.prototype['extensionAttributes'] = undefined;



  return exports;
}));


