/**
 * Magento Enterprise Edition 2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.magento) {
      root.magento = {};
    }
    root.magento.CustomerDataValidationResultsInterface = factory(root.magento.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CustomerDataValidationResultsInterface model module.
   * @module model/CustomerDataValidationResultsInterface
   * @version 2.0
   */

  /**
   * Constructs a new <code>CustomerDataValidationResultsInterface</code>.
   * Validation results interface.
   * @alias module:model/CustomerDataValidationResultsInterface
   * @class
   * @param valid {Boolean} If the provided data is valid.
   * @param messages {Array.<String>} Error messages as array in case of validation failure, else return empty array.
   */
  var exports = function(valid, messages) {
    var _this = this;

    _this['valid'] = valid;
    _this['messages'] = messages;
  };

  /**
   * Constructs a <code>CustomerDataValidationResultsInterface</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CustomerDataValidationResultsInterface} obj Optional instance to populate.
   * @return {module:model/CustomerDataValidationResultsInterface} The populated <code>CustomerDataValidationResultsInterface</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('valid')) {
        obj['valid'] = ApiClient.convertToType(data['valid'], 'Boolean');
      }
      if (data.hasOwnProperty('messages')) {
        obj['messages'] = ApiClient.convertToType(data['messages'], ['String']);
      }
    }
    return obj;
  }

  /**
   * If the provided data is valid.
   * @member {Boolean} valid
   */
  exports.prototype['valid'] = undefined;
  /**
   * Error messages as array in case of validation failure, else return empty array.
   * @member {Array.<String>} messages
   */
  exports.prototype['messages'] = undefined;



  return exports;
}));


