/**
 * Magento Enterprise Edition 2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CustomerDataRegionExtensionInterface'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CustomerDataRegionExtensionInterface'));
  } else {
    // Browser globals (root is window)
    if (!root.magento) {
      root.magento = {};
    }
    root.magento.CustomerDataRegionInterface = factory(root.magento.ApiClient, root.magento.CustomerDataRegionExtensionInterface);
  }
}(this, function(ApiClient, CustomerDataRegionExtensionInterface) {
  'use strict';




  /**
   * The CustomerDataRegionInterface model module.
   * @module model/CustomerDataRegionInterface
   * @version 2.0
   */

  /**
   * Constructs a new <code>CustomerDataRegionInterface</code>.
   * Customer address region interface.
   * @alias module:model/CustomerDataRegionInterface
   * @class
   * @param regionCode {String} Region code
   * @param region {String} Region
   * @param regionId {Number} Region id
   */
  var exports = function(regionCode, region, regionId) {
    var _this = this;

    _this['regionCode'] = regionCode;
    _this['region'] = region;
    _this['regionId'] = regionId;

  };

  /**
   * Constructs a <code>CustomerDataRegionInterface</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CustomerDataRegionInterface} obj Optional instance to populate.
   * @return {module:model/CustomerDataRegionInterface} The populated <code>CustomerDataRegionInterface</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('regionCode')) {
        obj['regionCode'] = ApiClient.convertToType(data['regionCode'], 'String');
      }
      if (data.hasOwnProperty('region')) {
        obj['region'] = ApiClient.convertToType(data['region'], 'String');
      }
      if (data.hasOwnProperty('regionId')) {
        obj['regionId'] = ApiClient.convertToType(data['regionId'], 'Number');
      }
      if (data.hasOwnProperty('extensionAttributes')) {
        obj['extensionAttributes'] = CustomerDataRegionExtensionInterface.constructFromObject(data['extensionAttributes']);
      }
    }
    return obj;
  }

  /**
   * Region code
   * @member {String} regionCode
   */
  exports.prototype['regionCode'] = undefined;
  /**
   * Region
   * @member {String} region
   */
  exports.prototype['region'] = undefined;
  /**
   * Region id
   * @member {Number} regionId
   */
  exports.prototype['regionId'] = undefined;
  /**
   * @member {module:model/CustomerDataRegionExtensionInterface} extensionAttributes
   */
  exports.prototype['extensionAttributes'] = undefined;



  return exports;
}));


