/**
 * Magento Enterprise Edition 2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CustomerDataAddressInterface', 'model/CustomerDataCustomerExtensionInterface', 'model/FrameworkAttributeInterface'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CustomerDataAddressInterface'), require('./CustomerDataCustomerExtensionInterface'), require('./FrameworkAttributeInterface'));
  } else {
    // Browser globals (root is window)
    if (!root.magento) {
      root.magento = {};
    }
    root.magento.CustomerDataCustomerInterface = factory(root.magento.ApiClient, root.magento.CustomerDataAddressInterface, root.magento.CustomerDataCustomerExtensionInterface, root.magento.FrameworkAttributeInterface);
  }
}(this, function(ApiClient, CustomerDataAddressInterface, CustomerDataCustomerExtensionInterface, FrameworkAttributeInterface) {
  'use strict';




  /**
   * The CustomerDataCustomerInterface model module.
   * @module model/CustomerDataCustomerInterface
   * @version 2.0
   */

  /**
   * Constructs a new <code>CustomerDataCustomerInterface</code>.
   * Customer interface.
   * @alias module:model/CustomerDataCustomerInterface
   * @class
   * @param email {String} Email address
   * @param firstname {String} First name
   * @param lastname {String} Last name
   */
  var exports = function(email, firstname, lastname) {
    var _this = this;










    _this['email'] = email;
    _this['firstname'] = firstname;
    _this['lastname'] = lastname;











  };

  /**
   * Constructs a <code>CustomerDataCustomerInterface</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CustomerDataCustomerInterface} obj Optional instance to populate.
   * @return {module:model/CustomerDataCustomerInterface} The populated <code>CustomerDataCustomerInterface</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('groupId')) {
        obj['groupId'] = ApiClient.convertToType(data['groupId'], 'Number');
      }
      if (data.hasOwnProperty('defaultBilling')) {
        obj['defaultBilling'] = ApiClient.convertToType(data['defaultBilling'], 'String');
      }
      if (data.hasOwnProperty('defaultShipping')) {
        obj['defaultShipping'] = ApiClient.convertToType(data['defaultShipping'], 'String');
      }
      if (data.hasOwnProperty('confirmation')) {
        obj['confirmation'] = ApiClient.convertToType(data['confirmation'], 'String');
      }
      if (data.hasOwnProperty('createdAt')) {
        obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'String');
      }
      if (data.hasOwnProperty('updatedAt')) {
        obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'String');
      }
      if (data.hasOwnProperty('createdIn')) {
        obj['createdIn'] = ApiClient.convertToType(data['createdIn'], 'String');
      }
      if (data.hasOwnProperty('dob')) {
        obj['dob'] = ApiClient.convertToType(data['dob'], 'String');
      }
      if (data.hasOwnProperty('email')) {
        obj['email'] = ApiClient.convertToType(data['email'], 'String');
      }
      if (data.hasOwnProperty('firstname')) {
        obj['firstname'] = ApiClient.convertToType(data['firstname'], 'String');
      }
      if (data.hasOwnProperty('lastname')) {
        obj['lastname'] = ApiClient.convertToType(data['lastname'], 'String');
      }
      if (data.hasOwnProperty('middlename')) {
        obj['middlename'] = ApiClient.convertToType(data['middlename'], 'String');
      }
      if (data.hasOwnProperty('prefix')) {
        obj['prefix'] = ApiClient.convertToType(data['prefix'], 'String');
      }
      if (data.hasOwnProperty('suffix')) {
        obj['suffix'] = ApiClient.convertToType(data['suffix'], 'String');
      }
      if (data.hasOwnProperty('gender')) {
        obj['gender'] = ApiClient.convertToType(data['gender'], 'Number');
      }
      if (data.hasOwnProperty('storeId')) {
        obj['storeId'] = ApiClient.convertToType(data['storeId'], 'Number');
      }
      if (data.hasOwnProperty('taxvat')) {
        obj['taxvat'] = ApiClient.convertToType(data['taxvat'], 'String');
      }
      if (data.hasOwnProperty('websiteId')) {
        obj['websiteId'] = ApiClient.convertToType(data['websiteId'], 'Number');
      }
      if (data.hasOwnProperty('addresses')) {
        obj['addresses'] = ApiClient.convertToType(data['addresses'], [CustomerDataAddressInterface]);
      }
      if (data.hasOwnProperty('disableAutoGroupChange')) {
        obj['disableAutoGroupChange'] = ApiClient.convertToType(data['disableAutoGroupChange'], 'Number');
      }
      if (data.hasOwnProperty('extensionAttributes')) {
        obj['extensionAttributes'] = CustomerDataCustomerExtensionInterface.constructFromObject(data['extensionAttributes']);
      }
      if (data.hasOwnProperty('customAttributes')) {
        obj['customAttributes'] = ApiClient.convertToType(data['customAttributes'], [FrameworkAttributeInterface]);
      }
    }
    return obj;
  }

  /**
   * Customer id
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * Group id
   * @member {Number} groupId
   */
  exports.prototype['groupId'] = undefined;
  /**
   * Default billing address id
   * @member {String} defaultBilling
   */
  exports.prototype['defaultBilling'] = undefined;
  /**
   * Default shipping address id
   * @member {String} defaultShipping
   */
  exports.prototype['defaultShipping'] = undefined;
  /**
   * Confirmation
   * @member {String} confirmation
   */
  exports.prototype['confirmation'] = undefined;
  /**
   * Created at time
   * @member {String} createdAt
   */
  exports.prototype['createdAt'] = undefined;
  /**
   * Updated at time
   * @member {String} updatedAt
   */
  exports.prototype['updatedAt'] = undefined;
  /**
   * Created in area
   * @member {String} createdIn
   */
  exports.prototype['createdIn'] = undefined;
  /**
   * Date of birth
   * @member {String} dob
   */
  exports.prototype['dob'] = undefined;
  /**
   * Email address
   * @member {String} email
   */
  exports.prototype['email'] = undefined;
  /**
   * First name
   * @member {String} firstname
   */
  exports.prototype['firstname'] = undefined;
  /**
   * Last name
   * @member {String} lastname
   */
  exports.prototype['lastname'] = undefined;
  /**
   * Middle name
   * @member {String} middlename
   */
  exports.prototype['middlename'] = undefined;
  /**
   * Prefix
   * @member {String} prefix
   */
  exports.prototype['prefix'] = undefined;
  /**
   * Suffix
   * @member {String} suffix
   */
  exports.prototype['suffix'] = undefined;
  /**
   * Gender
   * @member {Number} gender
   */
  exports.prototype['gender'] = undefined;
  /**
   * Store id
   * @member {Number} storeId
   */
  exports.prototype['storeId'] = undefined;
  /**
   * Tax Vat
   * @member {String} taxvat
   */
  exports.prototype['taxvat'] = undefined;
  /**
   * Website id
   * @member {Number} websiteId
   */
  exports.prototype['websiteId'] = undefined;
  /**
   * Customer addresses.
   * @member {Array.<module:model/CustomerDataAddressInterface>} addresses
   */
  exports.prototype['addresses'] = undefined;
  /**
   * Disable auto group change flag.
   * @member {Number} disableAutoGroupChange
   */
  exports.prototype['disableAutoGroupChange'] = undefined;
  /**
   * @member {module:model/CustomerDataCustomerExtensionInterface} extensionAttributes
   */
  exports.prototype['extensionAttributes'] = undefined;
  /**
   * Custom attributes values.
   * @member {Array.<module:model/FrameworkAttributeInterface>} customAttributes
   */
  exports.prototype['customAttributes'] = undefined;



  return exports;
}));


