/**
 * Magento Enterprise Edition 2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.magento) {
      root.magento = {};
    }
    root.magento.FrameworkSearchAggregationValueInterface = factory(root.magento.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The FrameworkSearchAggregationValueInterface model module.
   * @module model/FrameworkSearchAggregationValueInterface
   * @version 2.0
   */

  /**
   * Constructs a new <code>FrameworkSearchAggregationValueInterface</code>.
   * 
   * @alias module:model/FrameworkSearchAggregationValueInterface
   * @class
   * @param value {String} Aggregation
   * @param metrics {Array.<String>} Metrics
   */
  var exports = function(value, metrics) {
    var _this = this;

    _this['value'] = value;
    _this['metrics'] = metrics;
  };

  /**
   * Constructs a <code>FrameworkSearchAggregationValueInterface</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FrameworkSearchAggregationValueInterface} obj Optional instance to populate.
   * @return {module:model/FrameworkSearchAggregationValueInterface} The populated <code>FrameworkSearchAggregationValueInterface</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('value')) {
        obj['value'] = ApiClient.convertToType(data['value'], 'String');
      }
      if (data.hasOwnProperty('metrics')) {
        obj['metrics'] = ApiClient.convertToType(data['metrics'], ['String']);
      }
    }
    return obj;
  }

  /**
   * Aggregation
   * @member {String} value
   */
  exports.prototype['value'] = undefined;
  /**
   * Metrics
   * @member {Array.<String>} metrics
   */
  exports.prototype['metrics'] = undefined;



  return exports;
}));


