/**
 * Magento Enterprise Edition 2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GiftCardDataGiftcardAmountExtensionInterface'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./GiftCardDataGiftcardAmountExtensionInterface'));
  } else {
    // Browser globals (root is window)
    if (!root.magento) {
      root.magento = {};
    }
    root.magento.GiftCardDataGiftcardAmountInterface = factory(root.magento.ApiClient, root.magento.GiftCardDataGiftcardAmountExtensionInterface);
  }
}(this, function(ApiClient, GiftCardDataGiftcardAmountExtensionInterface) {
  'use strict';




  /**
   * The GiftCardDataGiftcardAmountInterface model module.
   * @module model/GiftCardDataGiftcardAmountInterface
   * @version 2.0
   */

  /**
   * Constructs a new <code>GiftCardDataGiftcardAmountInterface</code>.
   * Interface GiftcardAmountInterface: this interface is used to serialize and deserialize EAV attribute giftcard_amounts
   * @alias module:model/GiftCardDataGiftcardAmountInterface
   * @class
   * @param websiteId {Number} 
   * @param value {Number} 
   * @param websiteValue {Number} 
   */
  var exports = function(websiteId, value, websiteValue) {
    var _this = this;

    _this['websiteId'] = websiteId;
    _this['value'] = value;
    _this['websiteValue'] = websiteValue;

  };

  /**
   * Constructs a <code>GiftCardDataGiftcardAmountInterface</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GiftCardDataGiftcardAmountInterface} obj Optional instance to populate.
   * @return {module:model/GiftCardDataGiftcardAmountInterface} The populated <code>GiftCardDataGiftcardAmountInterface</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('websiteId')) {
        obj['websiteId'] = ApiClient.convertToType(data['websiteId'], 'Number');
      }
      if (data.hasOwnProperty('value')) {
        obj['value'] = ApiClient.convertToType(data['value'], 'Number');
      }
      if (data.hasOwnProperty('websiteValue')) {
        obj['websiteValue'] = ApiClient.convertToType(data['websiteValue'], 'Number');
      }
      if (data.hasOwnProperty('extensionAttributes')) {
        obj['extensionAttributes'] = GiftCardDataGiftcardAmountExtensionInterface.constructFromObject(data['extensionAttributes']);
      }
    }
    return obj;
  }

  /**
   * @member {Number} websiteId
   */
  exports.prototype['websiteId'] = undefined;
  /**
   * @member {Number} value
   */
  exports.prototype['value'] = undefined;
  /**
   * @member {Number} websiteValue
   */
  exports.prototype['websiteValue'] = undefined;
  /**
   * @member {module:model/GiftCardDataGiftcardAmountExtensionInterface} extensionAttributes
   */
  exports.prototype['extensionAttributes'] = undefined;



  return exports;
}));


