/**
 * Magento Enterprise Edition 2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GiftMessageDataMessageExtensionInterface'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./GiftMessageDataMessageExtensionInterface'));
  } else {
    // Browser globals (root is window)
    if (!root.magento) {
      root.magento = {};
    }
    root.magento.GiftMessageDataMessageInterface = factory(root.magento.ApiClient, root.magento.GiftMessageDataMessageExtensionInterface);
  }
}(this, function(ApiClient, GiftMessageDataMessageExtensionInterface) {
  'use strict';




  /**
   * The GiftMessageDataMessageInterface model module.
   * @module model/GiftMessageDataMessageInterface
   * @version 2.0
   */

  /**
   * Constructs a new <code>GiftMessageDataMessageInterface</code>.
   * 
   * @alias module:model/GiftMessageDataMessageInterface
   * @class
   * @param sender {String} Sender name.
   * @param recipient {String} Recipient name.
   * @param message {String} Message text.
   */
  var exports = function(sender, recipient, message) {
    var _this = this;



    _this['sender'] = sender;
    _this['recipient'] = recipient;
    _this['message'] = message;

  };

  /**
   * Constructs a <code>GiftMessageDataMessageInterface</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GiftMessageDataMessageInterface} obj Optional instance to populate.
   * @return {module:model/GiftMessageDataMessageInterface} The populated <code>GiftMessageDataMessageInterface</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('giftMessageId')) {
        obj['giftMessageId'] = ApiClient.convertToType(data['giftMessageId'], 'Number');
      }
      if (data.hasOwnProperty('customerId')) {
        obj['customerId'] = ApiClient.convertToType(data['customerId'], 'Number');
      }
      if (data.hasOwnProperty('sender')) {
        obj['sender'] = ApiClient.convertToType(data['sender'], 'String');
      }
      if (data.hasOwnProperty('recipient')) {
        obj['recipient'] = ApiClient.convertToType(data['recipient'], 'String');
      }
      if (data.hasOwnProperty('message')) {
        obj['message'] = ApiClient.convertToType(data['message'], 'String');
      }
      if (data.hasOwnProperty('extensionAttributes')) {
        obj['extensionAttributes'] = GiftMessageDataMessageExtensionInterface.constructFromObject(data['extensionAttributes']);
      }
    }
    return obj;
  }

  /**
   * Gift message ID. Otherwise, null.
   * @member {Number} giftMessageId
   */
  exports.prototype['giftMessageId'] = undefined;
  /**
   * Customer ID. Otherwise, null.
   * @member {Number} customerId
   */
  exports.prototype['customerId'] = undefined;
  /**
   * Sender name.
   * @member {String} sender
   */
  exports.prototype['sender'] = undefined;
  /**
   * Recipient name.
   * @member {String} recipient
   */
  exports.prototype['recipient'] = undefined;
  /**
   * Message text.
   * @member {String} message
   */
  exports.prototype['message'] = undefined;
  /**
   * @member {module:model/GiftMessageDataMessageExtensionInterface} extensionAttributes
   */
  exports.prototype['extensionAttributes'] = undefined;



  return exports;
}));


