/**
 * Magento Enterprise Edition 2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/FrameworkAttributeInterface', 'model/QuoteDataTotalsAdditionalDataExtensionInterface'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./FrameworkAttributeInterface'), require('./QuoteDataTotalsAdditionalDataExtensionInterface'));
  } else {
    // Browser globals (root is window)
    if (!root.magento) {
      root.magento = {};
    }
    root.magento.QuoteDataTotalsAdditionalDataInterface = factory(root.magento.ApiClient, root.magento.FrameworkAttributeInterface, root.magento.QuoteDataTotalsAdditionalDataExtensionInterface);
  }
}(this, function(ApiClient, FrameworkAttributeInterface, QuoteDataTotalsAdditionalDataExtensionInterface) {
  'use strict';




  /**
   * The QuoteDataTotalsAdditionalDataInterface model module.
   * @module model/QuoteDataTotalsAdditionalDataInterface
   * @version 2.0
   */

  /**
   * Constructs a new <code>QuoteDataTotalsAdditionalDataInterface</code>.
   * Additional data for totals collection.
   * @alias module:model/QuoteDataTotalsAdditionalDataInterface
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>QuoteDataTotalsAdditionalDataInterface</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/QuoteDataTotalsAdditionalDataInterface} obj Optional instance to populate.
   * @return {module:model/QuoteDataTotalsAdditionalDataInterface} The populated <code>QuoteDataTotalsAdditionalDataInterface</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('extensionAttributes')) {
        obj['extensionAttributes'] = QuoteDataTotalsAdditionalDataExtensionInterface.constructFromObject(data['extensionAttributes']);
      }
      if (data.hasOwnProperty('customAttributes')) {
        obj['customAttributes'] = ApiClient.convertToType(data['customAttributes'], [FrameworkAttributeInterface]);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/QuoteDataTotalsAdditionalDataExtensionInterface} extensionAttributes
   */
  exports.prototype['extensionAttributes'] = undefined;
  /**
   * Custom attributes values.
   * @member {Array.<module:model/FrameworkAttributeInterface>} customAttributes
   */
  exports.prototype['customAttributes'] = undefined;



  return exports;
}));


