/**
 * Magento Enterprise Edition 2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/QuoteDataPaymentExtensionInterface'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./QuoteDataPaymentExtensionInterface'));
  } else {
    // Browser globals (root is window)
    if (!root.magento) {
      root.magento = {};
    }
    root.magento.QuoteDataPaymentInterface = factory(root.magento.ApiClient, root.magento.QuoteDataPaymentExtensionInterface);
  }
}(this, function(ApiClient, QuoteDataPaymentExtensionInterface) {
  'use strict';




  /**
   * The QuoteDataPaymentInterface model module.
   * @module model/QuoteDataPaymentInterface
   * @version 2.0
   */

  /**
   * Constructs a new <code>QuoteDataPaymentInterface</code>.
   * Interface PaymentInterface
   * @alias module:model/QuoteDataPaymentInterface
   * @class
   * @param method {String} Payment method code
   */
  var exports = function(method) {
    var _this = this;


    _this['method'] = method;


  };

  /**
   * Constructs a <code>QuoteDataPaymentInterface</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/QuoteDataPaymentInterface} obj Optional instance to populate.
   * @return {module:model/QuoteDataPaymentInterface} The populated <code>QuoteDataPaymentInterface</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('poNumber')) {
        obj['poNumber'] = ApiClient.convertToType(data['poNumber'], 'String');
      }
      if (data.hasOwnProperty('method')) {
        obj['method'] = ApiClient.convertToType(data['method'], 'String');
      }
      if (data.hasOwnProperty('additionalData')) {
        obj['additionalData'] = ApiClient.convertToType(data['additionalData'], ['String']);
      }
      if (data.hasOwnProperty('extensionAttributes')) {
        obj['extensionAttributes'] = QuoteDataPaymentExtensionInterface.constructFromObject(data['extensionAttributes']);
      }
    }
    return obj;
  }

  /**
   * Purchase order number
   * @member {String} poNumber
   */
  exports.prototype['poNumber'] = undefined;
  /**
   * Payment method code
   * @member {String} method
   */
  exports.prototype['method'] = undefined;
  /**
   * Payment additional details
   * @member {Array.<String>} additionalData
   */
  exports.prototype['additionalData'] = undefined;
  /**
   * @member {module:model/QuoteDataPaymentExtensionInterface} extensionAttributes
   */
  exports.prototype['extensionAttributes'] = undefined;



  return exports;
}));


