/**
 * Magento Enterprise Edition 2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/QuoteDataProductOptionExtensionInterface'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./QuoteDataProductOptionExtensionInterface'));
  } else {
    // Browser globals (root is window)
    if (!root.magento) {
      root.magento = {};
    }
    root.magento.QuoteDataProductOptionInterface = factory(root.magento.ApiClient, root.magento.QuoteDataProductOptionExtensionInterface);
  }
}(this, function(ApiClient, QuoteDataProductOptionExtensionInterface) {
  'use strict';




  /**
   * The QuoteDataProductOptionInterface model module.
   * @module model/QuoteDataProductOptionInterface
   * @version 2.0
   */

  /**
   * Constructs a new <code>QuoteDataProductOptionInterface</code>.
   * Product option interface
   * @alias module:model/QuoteDataProductOptionInterface
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>QuoteDataProductOptionInterface</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/QuoteDataProductOptionInterface} obj Optional instance to populate.
   * @return {module:model/QuoteDataProductOptionInterface} The populated <code>QuoteDataProductOptionInterface</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('extensionAttributes')) {
        obj['extensionAttributes'] = QuoteDataProductOptionExtensionInterface.constructFromObject(data['extensionAttributes']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/QuoteDataProductOptionExtensionInterface} extensionAttributes
   */
  exports.prototype['extensionAttributes'] = undefined;



  return exports;
}));


