/**
 * Magento Enterprise Edition 2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/QuoteDataTotalSegmentInterface', 'model/QuoteDataTotalsExtensionInterface', 'model/QuoteDataTotalsItemInterface'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./QuoteDataTotalSegmentInterface'), require('./QuoteDataTotalsExtensionInterface'), require('./QuoteDataTotalsItemInterface'));
  } else {
    // Browser globals (root is window)
    if (!root.magento) {
      root.magento = {};
    }
    root.magento.QuoteDataTotalsInterface = factory(root.magento.ApiClient, root.magento.QuoteDataTotalSegmentInterface, root.magento.QuoteDataTotalsExtensionInterface, root.magento.QuoteDataTotalsItemInterface);
  }
}(this, function(ApiClient, QuoteDataTotalSegmentInterface, QuoteDataTotalsExtensionInterface, QuoteDataTotalsItemInterface) {
  'use strict';




  /**
   * The QuoteDataTotalsInterface model module.
   * @module model/QuoteDataTotalsInterface
   * @version 2.0
   */

  /**
   * Constructs a new <code>QuoteDataTotalsInterface</code>.
   * Interface TotalsInterface
   * @alias module:model/QuoteDataTotalsInterface
   * @class
   * @param weeeTaxAppliedAmount {Number} Item weee tax applied amount in quote currency.
   * @param totalSegments {Array.<module:model/QuoteDataTotalSegmentInterface>} Dynamically calculated totals
   */
  var exports = function(weeeTaxAppliedAmount, totalSegments) {
    var _this = this;















    _this['weeeTaxAppliedAmount'] = weeeTaxAppliedAmount;











    _this['totalSegments'] = totalSegments;

  };

  /**
   * Constructs a <code>QuoteDataTotalsInterface</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/QuoteDataTotalsInterface} obj Optional instance to populate.
   * @return {module:model/QuoteDataTotalsInterface} The populated <code>QuoteDataTotalsInterface</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('grandTotal')) {
        obj['grandTotal'] = ApiClient.convertToType(data['grandTotal'], 'Number');
      }
      if (data.hasOwnProperty('baseGrandTotal')) {
        obj['baseGrandTotal'] = ApiClient.convertToType(data['baseGrandTotal'], 'Number');
      }
      if (data.hasOwnProperty('subtotal')) {
        obj['subtotal'] = ApiClient.convertToType(data['subtotal'], 'Number');
      }
      if (data.hasOwnProperty('baseSubtotal')) {
        obj['baseSubtotal'] = ApiClient.convertToType(data['baseSubtotal'], 'Number');
      }
      if (data.hasOwnProperty('discountAmount')) {
        obj['discountAmount'] = ApiClient.convertToType(data['discountAmount'], 'Number');
      }
      if (data.hasOwnProperty('baseDiscountAmount')) {
        obj['baseDiscountAmount'] = ApiClient.convertToType(data['baseDiscountAmount'], 'Number');
      }
      if (data.hasOwnProperty('subtotalWithDiscount')) {
        obj['subtotalWithDiscount'] = ApiClient.convertToType(data['subtotalWithDiscount'], 'Number');
      }
      if (data.hasOwnProperty('baseSubtotalWithDiscount')) {
        obj['baseSubtotalWithDiscount'] = ApiClient.convertToType(data['baseSubtotalWithDiscount'], 'Number');
      }
      if (data.hasOwnProperty('shippingAmount')) {
        obj['shippingAmount'] = ApiClient.convertToType(data['shippingAmount'], 'Number');
      }
      if (data.hasOwnProperty('baseShippingAmount')) {
        obj['baseShippingAmount'] = ApiClient.convertToType(data['baseShippingAmount'], 'Number');
      }
      if (data.hasOwnProperty('shippingDiscountAmount')) {
        obj['shippingDiscountAmount'] = ApiClient.convertToType(data['shippingDiscountAmount'], 'Number');
      }
      if (data.hasOwnProperty('baseShippingDiscountAmount')) {
        obj['baseShippingDiscountAmount'] = ApiClient.convertToType(data['baseShippingDiscountAmount'], 'Number');
      }
      if (data.hasOwnProperty('taxAmount')) {
        obj['taxAmount'] = ApiClient.convertToType(data['taxAmount'], 'Number');
      }
      if (data.hasOwnProperty('baseTaxAmount')) {
        obj['baseTaxAmount'] = ApiClient.convertToType(data['baseTaxAmount'], 'Number');
      }
      if (data.hasOwnProperty('weeeTaxAppliedAmount')) {
        obj['weeeTaxAppliedAmount'] = ApiClient.convertToType(data['weeeTaxAppliedAmount'], 'Number');
      }
      if (data.hasOwnProperty('shippingTaxAmount')) {
        obj['shippingTaxAmount'] = ApiClient.convertToType(data['shippingTaxAmount'], 'Number');
      }
      if (data.hasOwnProperty('baseShippingTaxAmount')) {
        obj['baseShippingTaxAmount'] = ApiClient.convertToType(data['baseShippingTaxAmount'], 'Number');
      }
      if (data.hasOwnProperty('subtotalInclTax')) {
        obj['subtotalInclTax'] = ApiClient.convertToType(data['subtotalInclTax'], 'Number');
      }
      if (data.hasOwnProperty('baseSubtotalInclTax')) {
        obj['baseSubtotalInclTax'] = ApiClient.convertToType(data['baseSubtotalInclTax'], 'Number');
      }
      if (data.hasOwnProperty('shippingInclTax')) {
        obj['shippingInclTax'] = ApiClient.convertToType(data['shippingInclTax'], 'Number');
      }
      if (data.hasOwnProperty('baseShippingInclTax')) {
        obj['baseShippingInclTax'] = ApiClient.convertToType(data['baseShippingInclTax'], 'Number');
      }
      if (data.hasOwnProperty('baseCurrencyCode')) {
        obj['baseCurrencyCode'] = ApiClient.convertToType(data['baseCurrencyCode'], 'String');
      }
      if (data.hasOwnProperty('quoteCurrencyCode')) {
        obj['quoteCurrencyCode'] = ApiClient.convertToType(data['quoteCurrencyCode'], 'String');
      }
      if (data.hasOwnProperty('couponCode')) {
        obj['couponCode'] = ApiClient.convertToType(data['couponCode'], 'String');
      }
      if (data.hasOwnProperty('itemsQty')) {
        obj['itemsQty'] = ApiClient.convertToType(data['itemsQty'], 'Number');
      }
      if (data.hasOwnProperty('items')) {
        obj['items'] = ApiClient.convertToType(data['items'], [QuoteDataTotalsItemInterface]);
      }
      if (data.hasOwnProperty('totalSegments')) {
        obj['totalSegments'] = ApiClient.convertToType(data['totalSegments'], [QuoteDataTotalSegmentInterface]);
      }
      if (data.hasOwnProperty('extensionAttributes')) {
        obj['extensionAttributes'] = QuoteDataTotalsExtensionInterface.constructFromObject(data['extensionAttributes']);
      }
    }
    return obj;
  }

  /**
   * Grand total in quote currency
   * @member {Number} grandTotal
   */
  exports.prototype['grandTotal'] = undefined;
  /**
   * Grand total in base currency
   * @member {Number} baseGrandTotal
   */
  exports.prototype['baseGrandTotal'] = undefined;
  /**
   * Subtotal in quote currency
   * @member {Number} subtotal
   */
  exports.prototype['subtotal'] = undefined;
  /**
   * Subtotal in base currency
   * @member {Number} baseSubtotal
   */
  exports.prototype['baseSubtotal'] = undefined;
  /**
   * Discount amount in quote currency
   * @member {Number} discountAmount
   */
  exports.prototype['discountAmount'] = undefined;
  /**
   * Discount amount in base currency
   * @member {Number} baseDiscountAmount
   */
  exports.prototype['baseDiscountAmount'] = undefined;
  /**
   * Subtotal in quote currency with applied discount
   * @member {Number} subtotalWithDiscount
   */
  exports.prototype['subtotalWithDiscount'] = undefined;
  /**
   * Subtotal in base currency with applied discount
   * @member {Number} baseSubtotalWithDiscount
   */
  exports.prototype['baseSubtotalWithDiscount'] = undefined;
  /**
   * Shipping amount in quote currency
   * @member {Number} shippingAmount
   */
  exports.prototype['shippingAmount'] = undefined;
  /**
   * Shipping amount in base currency
   * @member {Number} baseShippingAmount
   */
  exports.prototype['baseShippingAmount'] = undefined;
  /**
   * Shipping discount amount in quote currency
   * @member {Number} shippingDiscountAmount
   */
  exports.prototype['shippingDiscountAmount'] = undefined;
  /**
   * Shipping discount amount in base currency
   * @member {Number} baseShippingDiscountAmount
   */
  exports.prototype['baseShippingDiscountAmount'] = undefined;
  /**
   * Tax amount in quote currency
   * @member {Number} taxAmount
   */
  exports.prototype['taxAmount'] = undefined;
  /**
   * Tax amount in base currency
   * @member {Number} baseTaxAmount
   */
  exports.prototype['baseTaxAmount'] = undefined;
  /**
   * Item weee tax applied amount in quote currency.
   * @member {Number} weeeTaxAppliedAmount
   */
  exports.prototype['weeeTaxAppliedAmount'] = undefined;
  /**
   * Shipping tax amount in quote currency
   * @member {Number} shippingTaxAmount
   */
  exports.prototype['shippingTaxAmount'] = undefined;
  /**
   * Shipping tax amount in base currency
   * @member {Number} baseShippingTaxAmount
   */
  exports.prototype['baseShippingTaxAmount'] = undefined;
  /**
   * Subtotal including tax in quote currency
   * @member {Number} subtotalInclTax
   */
  exports.prototype['subtotalInclTax'] = undefined;
  /**
   * Subtotal including tax in base currency
   * @member {Number} baseSubtotalInclTax
   */
  exports.prototype['baseSubtotalInclTax'] = undefined;
  /**
   * Shipping including tax in quote currency
   * @member {Number} shippingInclTax
   */
  exports.prototype['shippingInclTax'] = undefined;
  /**
   * Shipping including tax in base currency
   * @member {Number} baseShippingInclTax
   */
  exports.prototype['baseShippingInclTax'] = undefined;
  /**
   * Base currency code
   * @member {String} baseCurrencyCode
   */
  exports.prototype['baseCurrencyCode'] = undefined;
  /**
   * Quote currency code
   * @member {String} quoteCurrencyCode
   */
  exports.prototype['quoteCurrencyCode'] = undefined;
  /**
   * Applied coupon code
   * @member {String} couponCode
   */
  exports.prototype['couponCode'] = undefined;
  /**
   * Items qty
   * @member {Number} itemsQty
   */
  exports.prototype['itemsQty'] = undefined;
  /**
   * Totals by items
   * @member {Array.<module:model/QuoteDataTotalsItemInterface>} items
   */
  exports.prototype['items'] = undefined;
  /**
   * Dynamically calculated totals
   * @member {Array.<module:model/QuoteDataTotalSegmentInterface>} totalSegments
   */
  exports.prototype['totalSegments'] = undefined;
  /**
   * @member {module:model/QuoteDataTotalsExtensionInterface} extensionAttributes
   */
  exports.prototype['extensionAttributes'] = undefined;



  return exports;
}));


