/**
 * Magento Enterprise Edition 2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SalesDataCreditmemoCommentCreationExtensionInterface'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SalesDataCreditmemoCommentCreationExtensionInterface'));
  } else {
    // Browser globals (root is window)
    if (!root.magento) {
      root.magento = {};
    }
    root.magento.SalesDataCreditmemoCommentCreationInterface = factory(root.magento.ApiClient, root.magento.SalesDataCreditmemoCommentCreationExtensionInterface);
  }
}(this, function(ApiClient, SalesDataCreditmemoCommentCreationExtensionInterface) {
  'use strict';




  /**
   * The SalesDataCreditmemoCommentCreationInterface model module.
   * @module model/SalesDataCreditmemoCommentCreationInterface
   * @version 2.0
   */

  /**
   * Constructs a new <code>SalesDataCreditmemoCommentCreationInterface</code>.
   * Interface CreditmemoCommentCreationInterface
   * @alias module:model/SalesDataCreditmemoCommentCreationInterface
   * @class
   * @param comment {String} Comment.
   * @param isVisibleOnFront {Number} Is-visible-on-storefront flag value.
   */
  var exports = function(comment, isVisibleOnFront) {
    var _this = this;


    _this['comment'] = comment;
    _this['isVisibleOnFront'] = isVisibleOnFront;
  };

  /**
   * Constructs a <code>SalesDataCreditmemoCommentCreationInterface</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SalesDataCreditmemoCommentCreationInterface} obj Optional instance to populate.
   * @return {module:model/SalesDataCreditmemoCommentCreationInterface} The populated <code>SalesDataCreditmemoCommentCreationInterface</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('extensionAttributes')) {
        obj['extensionAttributes'] = SalesDataCreditmemoCommentCreationExtensionInterface.constructFromObject(data['extensionAttributes']);
      }
      if (data.hasOwnProperty('comment')) {
        obj['comment'] = ApiClient.convertToType(data['comment'], 'String');
      }
      if (data.hasOwnProperty('isVisibleOnFront')) {
        obj['isVisibleOnFront'] = ApiClient.convertToType(data['isVisibleOnFront'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/SalesDataCreditmemoCommentCreationExtensionInterface} extensionAttributes
   */
  exports.prototype['extensionAttributes'] = undefined;
  /**
   * Comment.
   * @member {String} comment
   */
  exports.prototype['comment'] = undefined;
  /**
   * Is-visible-on-storefront flag value.
   * @member {Number} isVisibleOnFront
   */
  exports.prototype['isVisibleOnFront'] = undefined;



  return exports;
}));


