/**
 * Magento Enterprise Edition 2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SalesDataCreditmemoCommentExtensionInterface'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SalesDataCreditmemoCommentExtensionInterface'));
  } else {
    // Browser globals (root is window)
    if (!root.magento) {
      root.magento = {};
    }
    root.magento.SalesDataCreditmemoCommentInterface = factory(root.magento.ApiClient, root.magento.SalesDataCreditmemoCommentExtensionInterface);
  }
}(this, function(ApiClient, SalesDataCreditmemoCommentExtensionInterface) {
  'use strict';




  /**
   * The SalesDataCreditmemoCommentInterface model module.
   * @module model/SalesDataCreditmemoCommentInterface
   * @version 2.0
   */

  /**
   * Constructs a new <code>SalesDataCreditmemoCommentInterface</code>.
   * Credit memo comment interface. After a customer places and pays for an order and an invoice has been issued, the merchant can create a credit memo to refund all or part of the amount paid for any returned or undelivered items. The memo restores funds to the customer account so that the customer can make future purchases. A credit memo usually includes comments that detail why the credit memo amount was credited to the customer.
   * @alias module:model/SalesDataCreditmemoCommentInterface
   * @class
   * @param comment {String} Comment.
   * @param isCustomerNotified {Number} Is-customer-notified flag value.
   * @param isVisibleOnFront {Number} Is-visible-on-storefront flag value.
   * @param parentId {Number} Parent ID.
   */
  var exports = function(comment, isCustomerNotified, isVisibleOnFront, parentId) {
    var _this = this;

    _this['comment'] = comment;


    _this['isCustomerNotified'] = isCustomerNotified;
    _this['isVisibleOnFront'] = isVisibleOnFront;
    _this['parentId'] = parentId;

  };

  /**
   * Constructs a <code>SalesDataCreditmemoCommentInterface</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SalesDataCreditmemoCommentInterface} obj Optional instance to populate.
   * @return {module:model/SalesDataCreditmemoCommentInterface} The populated <code>SalesDataCreditmemoCommentInterface</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('comment')) {
        obj['comment'] = ApiClient.convertToType(data['comment'], 'String');
      }
      if (data.hasOwnProperty('createdAt')) {
        obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'String');
      }
      if (data.hasOwnProperty('entityId')) {
        obj['entityId'] = ApiClient.convertToType(data['entityId'], 'Number');
      }
      if (data.hasOwnProperty('isCustomerNotified')) {
        obj['isCustomerNotified'] = ApiClient.convertToType(data['isCustomerNotified'], 'Number');
      }
      if (data.hasOwnProperty('isVisibleOnFront')) {
        obj['isVisibleOnFront'] = ApiClient.convertToType(data['isVisibleOnFront'], 'Number');
      }
      if (data.hasOwnProperty('parentId')) {
        obj['parentId'] = ApiClient.convertToType(data['parentId'], 'Number');
      }
      if (data.hasOwnProperty('extensionAttributes')) {
        obj['extensionAttributes'] = SalesDataCreditmemoCommentExtensionInterface.constructFromObject(data['extensionAttributes']);
      }
    }
    return obj;
  }

  /**
   * Comment.
   * @member {String} comment
   */
  exports.prototype['comment'] = undefined;
  /**
   * Created-at timestamp.
   * @member {String} createdAt
   */
  exports.prototype['createdAt'] = undefined;
  /**
   * Credit memo ID.
   * @member {Number} entityId
   */
  exports.prototype['entityId'] = undefined;
  /**
   * Is-customer-notified flag value.
   * @member {Number} isCustomerNotified
   */
  exports.prototype['isCustomerNotified'] = undefined;
  /**
   * Is-visible-on-storefront flag value.
   * @member {Number} isVisibleOnFront
   */
  exports.prototype['isVisibleOnFront'] = undefined;
  /**
   * Parent ID.
   * @member {Number} parentId
   */
  exports.prototype['parentId'] = undefined;
  /**
   * @member {module:model/SalesDataCreditmemoCommentExtensionInterface} extensionAttributes
   */
  exports.prototype['extensionAttributes'] = undefined;



  return exports;
}));


