/**
 * Magento Enterprise Edition 2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SalesDataTotalExtensionInterface'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SalesDataTotalExtensionInterface'));
  } else {
    // Browser globals (root is window)
    if (!root.magento) {
      root.magento = {};
    }
    root.magento.SalesDataTotalInterface = factory(root.magento.ApiClient, root.magento.SalesDataTotalExtensionInterface);
  }
}(this, function(ApiClient, SalesDataTotalExtensionInterface) {
  'use strict';




  /**
   * The SalesDataTotalInterface model module.
   * @module model/SalesDataTotalInterface
   * @version 2.0
   */

  /**
   * Constructs a new <code>SalesDataTotalInterface</code>.
   * Interface TotalInterface
   * @alias module:model/SalesDataTotalInterface
   * @class
   */
  var exports = function() {
    var _this = this;




















  };

  /**
   * Constructs a <code>SalesDataTotalInterface</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SalesDataTotalInterface} obj Optional instance to populate.
   * @return {module:model/SalesDataTotalInterface} The populated <code>SalesDataTotalInterface</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('baseShippingAmount')) {
        obj['baseShippingAmount'] = ApiClient.convertToType(data['baseShippingAmount'], 'Number');
      }
      if (data.hasOwnProperty('baseShippingCanceled')) {
        obj['baseShippingCanceled'] = ApiClient.convertToType(data['baseShippingCanceled'], 'Number');
      }
      if (data.hasOwnProperty('baseShippingDiscountAmount')) {
        obj['baseShippingDiscountAmount'] = ApiClient.convertToType(data['baseShippingDiscountAmount'], 'Number');
      }
      if (data.hasOwnProperty('baseShippingDiscountTaxCompensationAmnt')) {
        obj['baseShippingDiscountTaxCompensationAmnt'] = ApiClient.convertToType(data['baseShippingDiscountTaxCompensationAmnt'], 'Number');
      }
      if (data.hasOwnProperty('baseShippingInclTax')) {
        obj['baseShippingInclTax'] = ApiClient.convertToType(data['baseShippingInclTax'], 'Number');
      }
      if (data.hasOwnProperty('baseShippingInvoiced')) {
        obj['baseShippingInvoiced'] = ApiClient.convertToType(data['baseShippingInvoiced'], 'Number');
      }
      if (data.hasOwnProperty('baseShippingRefunded')) {
        obj['baseShippingRefunded'] = ApiClient.convertToType(data['baseShippingRefunded'], 'Number');
      }
      if (data.hasOwnProperty('baseShippingTaxAmount')) {
        obj['baseShippingTaxAmount'] = ApiClient.convertToType(data['baseShippingTaxAmount'], 'Number');
      }
      if (data.hasOwnProperty('baseShippingTaxRefunded')) {
        obj['baseShippingTaxRefunded'] = ApiClient.convertToType(data['baseShippingTaxRefunded'], 'Number');
      }
      if (data.hasOwnProperty('shippingAmount')) {
        obj['shippingAmount'] = ApiClient.convertToType(data['shippingAmount'], 'Number');
      }
      if (data.hasOwnProperty('shippingCanceled')) {
        obj['shippingCanceled'] = ApiClient.convertToType(data['shippingCanceled'], 'Number');
      }
      if (data.hasOwnProperty('shippingDiscountAmount')) {
        obj['shippingDiscountAmount'] = ApiClient.convertToType(data['shippingDiscountAmount'], 'Number');
      }
      if (data.hasOwnProperty('shippingDiscountTaxCompensationAmount')) {
        obj['shippingDiscountTaxCompensationAmount'] = ApiClient.convertToType(data['shippingDiscountTaxCompensationAmount'], 'Number');
      }
      if (data.hasOwnProperty('shippingInclTax')) {
        obj['shippingInclTax'] = ApiClient.convertToType(data['shippingInclTax'], 'Number');
      }
      if (data.hasOwnProperty('shippingInvoiced')) {
        obj['shippingInvoiced'] = ApiClient.convertToType(data['shippingInvoiced'], 'Number');
      }
      if (data.hasOwnProperty('shippingRefunded')) {
        obj['shippingRefunded'] = ApiClient.convertToType(data['shippingRefunded'], 'Number');
      }
      if (data.hasOwnProperty('shippingTaxAmount')) {
        obj['shippingTaxAmount'] = ApiClient.convertToType(data['shippingTaxAmount'], 'Number');
      }
      if (data.hasOwnProperty('shippingTaxRefunded')) {
        obj['shippingTaxRefunded'] = ApiClient.convertToType(data['shippingTaxRefunded'], 'Number');
      }
      if (data.hasOwnProperty('extensionAttributes')) {
        obj['extensionAttributes'] = SalesDataTotalExtensionInterface.constructFromObject(data['extensionAttributes']);
      }
    }
    return obj;
  }

  /**
   * Base shipping amount.
   * @member {Number} baseShippingAmount
   */
  exports.prototype['baseShippingAmount'] = undefined;
  /**
   * Base shipping canceled.
   * @member {Number} baseShippingCanceled
   */
  exports.prototype['baseShippingCanceled'] = undefined;
  /**
   * Base shipping discount amount.
   * @member {Number} baseShippingDiscountAmount
   */
  exports.prototype['baseShippingDiscountAmount'] = undefined;
  /**
   * Base shipping discount tax compensation amount.
   * @member {Number} baseShippingDiscountTaxCompensationAmnt
   */
  exports.prototype['baseShippingDiscountTaxCompensationAmnt'] = undefined;
  /**
   * Base shipping including tax.
   * @member {Number} baseShippingInclTax
   */
  exports.prototype['baseShippingInclTax'] = undefined;
  /**
   * Base shipping invoiced.
   * @member {Number} baseShippingInvoiced
   */
  exports.prototype['baseShippingInvoiced'] = undefined;
  /**
   * Base shipping refunded.
   * @member {Number} baseShippingRefunded
   */
  exports.prototype['baseShippingRefunded'] = undefined;
  /**
   * Base shipping tax amount.
   * @member {Number} baseShippingTaxAmount
   */
  exports.prototype['baseShippingTaxAmount'] = undefined;
  /**
   * Base shipping tax refunded.
   * @member {Number} baseShippingTaxRefunded
   */
  exports.prototype['baseShippingTaxRefunded'] = undefined;
  /**
   * Shipping amount.
   * @member {Number} shippingAmount
   */
  exports.prototype['shippingAmount'] = undefined;
  /**
   * Shipping canceled amount.
   * @member {Number} shippingCanceled
   */
  exports.prototype['shippingCanceled'] = undefined;
  /**
   * Shipping discount amount.
   * @member {Number} shippingDiscountAmount
   */
  exports.prototype['shippingDiscountAmount'] = undefined;
  /**
   * Shipping discount tax compensation amount.
   * @member {Number} shippingDiscountTaxCompensationAmount
   */
  exports.prototype['shippingDiscountTaxCompensationAmount'] = undefined;
  /**
   * Shipping including tax amount.
   * @member {Number} shippingInclTax
   */
  exports.prototype['shippingInclTax'] = undefined;
  /**
   * Shipping invoiced amount.
   * @member {Number} shippingInvoiced
   */
  exports.prototype['shippingInvoiced'] = undefined;
  /**
   * Shipping refunded amount.
   * @member {Number} shippingRefunded
   */
  exports.prototype['shippingRefunded'] = undefined;
  /**
   * Shipping tax amount.
   * @member {Number} shippingTaxAmount
   */
  exports.prototype['shippingTaxAmount'] = undefined;
  /**
   * Shipping tax refunded amount.
   * @member {Number} shippingTaxRefunded
   */
  exports.prototype['shippingTaxRefunded'] = undefined;
  /**
   * @member {module:model/SalesDataTotalExtensionInterface} extensionAttributes
   */
  exports.prototype['extensionAttributes'] = undefined;



  return exports;
}));


