/**
 * Magento Enterprise Edition 2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/TaxDataTaxClassExtensionInterface'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./TaxDataTaxClassExtensionInterface'));
  } else {
    // Browser globals (root is window)
    if (!root.magento) {
      root.magento = {};
    }
    root.magento.TaxDataTaxClassInterface = factory(root.magento.ApiClient, root.magento.TaxDataTaxClassExtensionInterface);
  }
}(this, function(ApiClient, TaxDataTaxClassExtensionInterface) {
  'use strict';




  /**
   * The TaxDataTaxClassInterface model module.
   * @module model/TaxDataTaxClassInterface
   * @version 2.0
   */

  /**
   * Constructs a new <code>TaxDataTaxClassInterface</code>.
   * Tax class interface.
   * @alias module:model/TaxDataTaxClassInterface
   * @class
   * @param className {String} Tax class name.
   * @param classType {String} Tax class type.
   */
  var exports = function(className, classType) {
    var _this = this;


    _this['className'] = className;
    _this['classType'] = classType;

  };

  /**
   * Constructs a <code>TaxDataTaxClassInterface</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TaxDataTaxClassInterface} obj Optional instance to populate.
   * @return {module:model/TaxDataTaxClassInterface} The populated <code>TaxDataTaxClassInterface</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('classId')) {
        obj['classId'] = ApiClient.convertToType(data['classId'], 'Number');
      }
      if (data.hasOwnProperty('className')) {
        obj['className'] = ApiClient.convertToType(data['className'], 'String');
      }
      if (data.hasOwnProperty('classType')) {
        obj['classType'] = ApiClient.convertToType(data['classType'], 'String');
      }
      if (data.hasOwnProperty('extensionAttributes')) {
        obj['extensionAttributes'] = TaxDataTaxClassExtensionInterface.constructFromObject(data['extensionAttributes']);
      }
    }
    return obj;
  }

  /**
   * Tax class ID.
   * @member {Number} classId
   */
  exports.prototype['classId'] = undefined;
  /**
   * Tax class name.
   * @member {String} className
   */
  exports.prototype['className'] = undefined;
  /**
   * Tax class type.
   * @member {String} classType
   */
  exports.prototype['classType'] = undefined;
  /**
   * @member {module:model/TaxDataTaxClassExtensionInterface} extensionAttributes
   */
  exports.prototype['extensionAttributes'] = undefined;



  return exports;
}));


