/**
 * Magento Enterprise Edition 2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CatalogDataCategoryAttributeInterface', 'model/CatalogDataCategoryAttributeSearchResultsInterface', 'model/ErrorResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/CatalogDataCategoryAttributeInterface'), require('../model/CatalogDataCategoryAttributeSearchResultsInterface'), require('../model/ErrorResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.magento) {
      root.magento = {};
    }
    root.magento.CatalogCategoryAttributeRepositoryV1Api = factory(root.magento.ApiClient, root.magento.CatalogDataCategoryAttributeInterface, root.magento.CatalogDataCategoryAttributeSearchResultsInterface, root.magento.ErrorResponse);
  }
}(this, function(ApiClient, CatalogDataCategoryAttributeInterface, CatalogDataCategoryAttributeSearchResultsInterface, ErrorResponse) {
  'use strict';

  /**
   * CatalogCategoryAttributeRepositoryV1 service.
   * @module api/CatalogCategoryAttributeRepositoryV1Api
   * @version 2.0
   */

  /**
   * Constructs a new CatalogCategoryAttributeRepositoryV1Api. 
   * @alias module:api/CatalogCategoryAttributeRepositoryV1Api
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the catalogCategoryAttributeRepositoryV1GetGet operation.
     * @callback module:api/CatalogCategoryAttributeRepositoryV1Api~catalogCategoryAttributeRepositoryV1GetGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CatalogDataCategoryAttributeInterface} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve specific attribute
     * @param {String} attributeCode 
     * @param {module:api/CatalogCategoryAttributeRepositoryV1Api~catalogCategoryAttributeRepositoryV1GetGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CatalogDataCategoryAttributeInterface}
     */
    this.catalogCategoryAttributeRepositoryV1GetGet = function(attributeCode, callback) {
      var postBody = null;

      // verify the required parameter 'attributeCode' is set
      if (attributeCode === undefined || attributeCode === null) {
        throw new Error("Missing the required parameter 'attributeCode' when calling catalogCategoryAttributeRepositoryV1GetGet");
      }


      var pathParams = {
        'attributeCode': attributeCode
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = CatalogDataCategoryAttributeInterface;

      return this.apiClient.callApi(
        '/V1/categories/attributes/{attributeCode}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the catalogCategoryAttributeRepositoryV1GetListGet operation.
     * @callback module:api/CatalogCategoryAttributeRepositoryV1Api~catalogCategoryAttributeRepositoryV1GetListGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CatalogDataCategoryAttributeSearchResultsInterface} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve all attributes for entity type
     * @param {Object} opts Optional parameters
     * @param {String} opts.searchCriteriaFilterGroupsFiltersField Field
     * @param {String} opts.searchCriteriaFilterGroupsFiltersValue Value
     * @param {String} opts.searchCriteriaFilterGroupsFiltersConditionType Condition type
     * @param {String} opts.searchCriteriaSortOrdersField Sorting field.
     * @param {String} opts.searchCriteriaSortOrdersDirection Sorting direction.
     * @param {Number} opts.searchCriteriaPageSize Page size.
     * @param {Number} opts.searchCriteriaCurrentPage Current page.
     * @param {module:api/CatalogCategoryAttributeRepositoryV1Api~catalogCategoryAttributeRepositoryV1GetListGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CatalogDataCategoryAttributeSearchResultsInterface}
     */
    this.catalogCategoryAttributeRepositoryV1GetListGet = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'searchCriteria[filterGroups][][filters][][field]': opts['searchCriteriaFilterGroupsFiltersField'],
        'searchCriteria[filterGroups][][filters][][value]': opts['searchCriteriaFilterGroupsFiltersValue'],
        'searchCriteria[filterGroups][][filters][][conditionType]': opts['searchCriteriaFilterGroupsFiltersConditionType'],
        'searchCriteria[sortOrders][][field]': opts['searchCriteriaSortOrdersField'],
        'searchCriteria[sortOrders][][direction]': opts['searchCriteriaSortOrdersDirection'],
        'searchCriteria[pageSize]': opts['searchCriteriaPageSize'],
        'searchCriteria[currentPage]': opts['searchCriteriaCurrentPage'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = CatalogDataCategoryAttributeSearchResultsInterface;

      return this.apiClient.callApi(
        '/V1/categories/attributes', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
