/**
 * Magento Enterprise Edition 2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CatalogDataCategoryProductLinkInterface', 'model/ErrorResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/CatalogDataCategoryProductLinkInterface'), require('../model/ErrorResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.magento) {
      root.magento = {};
    }
    root.magento.CatalogCategoryLinkManagementV1Api = factory(root.magento.ApiClient, root.magento.CatalogDataCategoryProductLinkInterface, root.magento.ErrorResponse);
  }
}(this, function(ApiClient, CatalogDataCategoryProductLinkInterface, ErrorResponse) {
  'use strict';

  /**
   * CatalogCategoryLinkManagementV1 service.
   * @module api/CatalogCategoryLinkManagementV1Api
   * @version 2.0
   */

  /**
   * Constructs a new CatalogCategoryLinkManagementV1Api. 
   * @alias module:api/CatalogCategoryLinkManagementV1Api
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the catalogCategoryLinkManagementV1GetAssignedProductsGet operation.
     * @callback module:api/CatalogCategoryLinkManagementV1Api~catalogCategoryLinkManagementV1GetAssignedProductsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CatalogDataCategoryProductLinkInterface>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get products assigned to category
     * @param {Number} categoryId 
     * @param {module:api/CatalogCategoryLinkManagementV1Api~catalogCategoryLinkManagementV1GetAssignedProductsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CatalogDataCategoryProductLinkInterface>}
     */
    this.catalogCategoryLinkManagementV1GetAssignedProductsGet = function(categoryId, callback) {
      var postBody = null;

      // verify the required parameter 'categoryId' is set
      if (categoryId === undefined || categoryId === null) {
        throw new Error("Missing the required parameter 'categoryId' when calling catalogCategoryLinkManagementV1GetAssignedProductsGet");
      }


      var pathParams = {
        'categoryId': categoryId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = [CatalogDataCategoryProductLinkInterface];

      return this.apiClient.callApi(
        '/V1/categories/{categoryId}/products', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
