/**
 * Magento Enterprise Edition 2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CheckoutAgreementsDataAgreementInterface', 'model/ErrorResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/CheckoutAgreementsDataAgreementInterface'), require('../model/ErrorResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.magento) {
      root.magento = {};
    }
    root.magento.CheckoutAgreementsCheckoutAgreementsRepositoryV1Api = factory(root.magento.ApiClient, root.magento.CheckoutAgreementsDataAgreementInterface, root.magento.ErrorResponse);
  }
}(this, function(ApiClient, CheckoutAgreementsDataAgreementInterface, ErrorResponse) {
  'use strict';

  /**
   * CheckoutAgreementsCheckoutAgreementsRepositoryV1 service.
   * @module api/CheckoutAgreementsCheckoutAgreementsRepositoryV1Api
   * @version 2.0
   */

  /**
   * Constructs a new CheckoutAgreementsCheckoutAgreementsRepositoryV1Api. 
   * @alias module:api/CheckoutAgreementsCheckoutAgreementsRepositoryV1Api
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the checkoutAgreementsCheckoutAgreementsRepositoryV1GetListGet operation.
     * @callback module:api/CheckoutAgreementsCheckoutAgreementsRepositoryV1Api~checkoutAgreementsCheckoutAgreementsRepositoryV1GetListGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CheckoutAgreementsDataAgreementInterface>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Lists active checkout agreements.
     * @param {module:api/CheckoutAgreementsCheckoutAgreementsRepositoryV1Api~checkoutAgreementsCheckoutAgreementsRepositoryV1GetListGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CheckoutAgreementsDataAgreementInterface>}
     */
    this.checkoutAgreementsCheckoutAgreementsRepositoryV1GetListGet = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = [CheckoutAgreementsDataAgreementInterface];

      return this.apiClient.callApi(
        '/V1/carts/licence', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
