/**
 * Magento Enterprise Edition 2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Body89', 'model/Body90', 'model/CheckoutDataPaymentDetailsInterface', 'model/ErrorResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Body89'), require('../model/Body90'), require('../model/CheckoutDataPaymentDetailsInterface'), require('../model/ErrorResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.magento) {
      root.magento = {};
    }
    root.magento.CheckoutGuestPaymentInformationManagementV1Api = factory(root.magento.ApiClient, root.magento.Body89, root.magento.Body90, root.magento.CheckoutDataPaymentDetailsInterface, root.magento.ErrorResponse);
  }
}(this, function(ApiClient, Body89, Body90, CheckoutDataPaymentDetailsInterface, ErrorResponse) {
  'use strict';

  /**
   * CheckoutGuestPaymentInformationManagementV1 service.
   * @module api/CheckoutGuestPaymentInformationManagementV1Api
   * @version 2.0
   */

  /**
   * Constructs a new CheckoutGuestPaymentInformationManagementV1Api. 
   * @alias module:api/CheckoutGuestPaymentInformationManagementV1Api
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the checkoutGuestPaymentInformationManagementV1GetPaymentInformationGet operation.
     * @callback module:api/CheckoutGuestPaymentInformationManagementV1Api~checkoutGuestPaymentInformationManagementV1GetPaymentInformationGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CheckoutDataPaymentDetailsInterface} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get payment information
     * @param {String} cartId 
     * @param {module:api/CheckoutGuestPaymentInformationManagementV1Api~checkoutGuestPaymentInformationManagementV1GetPaymentInformationGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CheckoutDataPaymentDetailsInterface}
     */
    this.checkoutGuestPaymentInformationManagementV1GetPaymentInformationGet = function(cartId, callback) {
      var postBody = null;

      // verify the required parameter 'cartId' is set
      if (cartId === undefined || cartId === null) {
        throw new Error("Missing the required parameter 'cartId' when calling checkoutGuestPaymentInformationManagementV1GetPaymentInformationGet");
      }


      var pathParams = {
        'cartId': cartId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = CheckoutDataPaymentDetailsInterface;

      return this.apiClient.callApi(
        '/V1/guest-carts/{cartId}/payment-information', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the checkoutGuestPaymentInformationManagementV1SavePaymentInformationAndPlaceOrderPost operation.
     * @callback module:api/CheckoutGuestPaymentInformationManagementV1Api~checkoutGuestPaymentInformationManagementV1SavePaymentInformationAndPlaceOrderPostCallback
     * @param {String} error Error message, if any.
     * @param {'Number'} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Set payment information and place order for a specified cart.
     * @param {String} cartId 
     * @param {Object} opts Optional parameters
     * @param {module:model/Body89} opts.body 
     * @param {module:api/CheckoutGuestPaymentInformationManagementV1Api~checkoutGuestPaymentInformationManagementV1SavePaymentInformationAndPlaceOrderPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link 'Number'}
     */
    this.checkoutGuestPaymentInformationManagementV1SavePaymentInformationAndPlaceOrderPost = function(cartId, opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];

      // verify the required parameter 'cartId' is set
      if (cartId === undefined || cartId === null) {
        throw new Error("Missing the required parameter 'cartId' when calling checkoutGuestPaymentInformationManagementV1SavePaymentInformationAndPlaceOrderPost");
      }


      var pathParams = {
        'cartId': cartId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = 'Number';

      return this.apiClient.callApi(
        '/V1/guest-carts/{cartId}/payment-information', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the checkoutGuestPaymentInformationManagementV1SavePaymentInformationPost operation.
     * @callback module:api/CheckoutGuestPaymentInformationManagementV1Api~checkoutGuestPaymentInformationManagementV1SavePaymentInformationPostCallback
     * @param {String} error Error message, if any.
     * @param {'Number'} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Set payment information for a specified cart.
     * @param {String} cartId 
     * @param {Object} opts Optional parameters
     * @param {module:model/Body90} opts.body 
     * @param {module:api/CheckoutGuestPaymentInformationManagementV1Api~checkoutGuestPaymentInformationManagementV1SavePaymentInformationPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link 'Number'}
     */
    this.checkoutGuestPaymentInformationManagementV1SavePaymentInformationPost = function(cartId, opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];

      // verify the required parameter 'cartId' is set
      if (cartId === undefined || cartId === null) {
        throw new Error("Missing the required parameter 'cartId' when calling checkoutGuestPaymentInformationManagementV1SavePaymentInformationPost");
      }


      var pathParams = {
        'cartId': cartId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = 'Number';

      return this.apiClient.callApi(
        '/V1/guest-carts/{cartId}/set-payment-information', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
