/**
 * Magento Enterprise Edition 2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CustomerDataAddressInterface', 'model/ErrorResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/CustomerDataAddressInterface'), require('../model/ErrorResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.magento) {
      root.magento = {};
    }
    root.magento.CustomerAddressRepositoryV1Api = factory(root.magento.ApiClient, root.magento.CustomerDataAddressInterface, root.magento.ErrorResponse);
  }
}(this, function(ApiClient, CustomerDataAddressInterface, ErrorResponse) {
  'use strict';

  /**
   * CustomerAddressRepositoryV1 service.
   * @module api/CustomerAddressRepositoryV1Api
   * @version 2.0
   */

  /**
   * Constructs a new CustomerAddressRepositoryV1Api. 
   * @alias module:api/CustomerAddressRepositoryV1Api
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the customerAddressRepositoryV1DeleteByIdDelete operation.
     * @callback module:api/CustomerAddressRepositoryV1Api~customerAddressRepositoryV1DeleteByIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param {'Boolean'} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete customer address by ID.
     * @param {Number} addressId 
     * @param {module:api/CustomerAddressRepositoryV1Api~customerAddressRepositoryV1DeleteByIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link 'Boolean'}
     */
    this.customerAddressRepositoryV1DeleteByIdDelete = function(addressId, callback) {
      var postBody = null;

      // verify the required parameter 'addressId' is set
      if (addressId === undefined || addressId === null) {
        throw new Error("Missing the required parameter 'addressId' when calling customerAddressRepositoryV1DeleteByIdDelete");
      }


      var pathParams = {
        'addressId': addressId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = 'Boolean';

      return this.apiClient.callApi(
        '/V1/addresses/{addressId}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the customerAddressRepositoryV1GetByIdGet operation.
     * @callback module:api/CustomerAddressRepositoryV1Api~customerAddressRepositoryV1GetByIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CustomerDataAddressInterface} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve customer address.
     * @param {Number} addressId 
     * @param {module:api/CustomerAddressRepositoryV1Api~customerAddressRepositoryV1GetByIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CustomerDataAddressInterface}
     */
    this.customerAddressRepositoryV1GetByIdGet = function(addressId, callback) {
      var postBody = null;

      // verify the required parameter 'addressId' is set
      if (addressId === undefined || addressId === null) {
        throw new Error("Missing the required parameter 'addressId' when calling customerAddressRepositoryV1GetByIdGet");
      }


      var pathParams = {
        'addressId': addressId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = CustomerDataAddressInterface;

      return this.apiClient.callApi(
        '/V1/customers/addresses/{addressId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
