/**
 * Magento Enterprise Edition 2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Body78', 'model/Body79', 'model/DownloadableDataLinkInterface', 'model/ErrorResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Body78'), require('../model/Body79'), require('../model/DownloadableDataLinkInterface'), require('../model/ErrorResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.magento) {
      root.magento = {};
    }
    root.magento.DownloadableLinkRepositoryV1Api = factory(root.magento.ApiClient, root.magento.Body78, root.magento.Body79, root.magento.DownloadableDataLinkInterface, root.magento.ErrorResponse);
  }
}(this, function(ApiClient, Body78, Body79, DownloadableDataLinkInterface, ErrorResponse) {
  'use strict';

  /**
   * DownloadableLinkRepositoryV1 service.
   * @module api/DownloadableLinkRepositoryV1Api
   * @version 2.0
   */

  /**
   * Constructs a new DownloadableLinkRepositoryV1Api. 
   * @alias module:api/DownloadableLinkRepositoryV1Api
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the downloadableLinkRepositoryV1DeleteDelete operation.
     * @callback module:api/DownloadableLinkRepositoryV1Api~downloadableLinkRepositoryV1DeleteDeleteCallback
     * @param {String} error Error message, if any.
     * @param {'Boolean'} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete downloadable link
     * @param {Number} id 
     * @param {module:api/DownloadableLinkRepositoryV1Api~downloadableLinkRepositoryV1DeleteDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link 'Boolean'}
     */
    this.downloadableLinkRepositoryV1DeleteDelete = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling downloadableLinkRepositoryV1DeleteDelete");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = 'Boolean';

      return this.apiClient.callApi(
        '/V1/products/downloadable-links/{id}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the downloadableLinkRepositoryV1GetListGet operation.
     * @callback module:api/DownloadableLinkRepositoryV1Api~downloadableLinkRepositoryV1GetListGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/DownloadableDataLinkInterface>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List of links with associated samples
     * @param {String} sku 
     * @param {module:api/DownloadableLinkRepositoryV1Api~downloadableLinkRepositoryV1GetListGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/DownloadableDataLinkInterface>}
     */
    this.downloadableLinkRepositoryV1GetListGet = function(sku, callback) {
      var postBody = null;

      // verify the required parameter 'sku' is set
      if (sku === undefined || sku === null) {
        throw new Error("Missing the required parameter 'sku' when calling downloadableLinkRepositoryV1GetListGet");
      }


      var pathParams = {
        'sku': sku
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = [DownloadableDataLinkInterface];

      return this.apiClient.callApi(
        '/V1/products/{sku}/downloadable-links', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the downloadableLinkRepositoryV1SavePost operation.
     * @callback module:api/DownloadableLinkRepositoryV1Api~downloadableLinkRepositoryV1SavePostCallback
     * @param {String} error Error message, if any.
     * @param {'Number'} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update downloadable link of the given product (link type and its resources cannot be changed)
     * @param {String} sku 
     * @param {Object} opts Optional parameters
     * @param {module:model/Body78} opts.body 
     * @param {module:api/DownloadableLinkRepositoryV1Api~downloadableLinkRepositoryV1SavePostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link 'Number'}
     */
    this.downloadableLinkRepositoryV1SavePost = function(sku, opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];

      // verify the required parameter 'sku' is set
      if (sku === undefined || sku === null) {
        throw new Error("Missing the required parameter 'sku' when calling downloadableLinkRepositoryV1SavePost");
      }


      var pathParams = {
        'sku': sku
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = 'Number';

      return this.apiClient.callApi(
        '/V1/products/{sku}/downloadable-links', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the downloadableLinkRepositoryV1SavePut operation.
     * @callback module:api/DownloadableLinkRepositoryV1Api~downloadableLinkRepositoryV1SavePutCallback
     * @param {String} error Error message, if any.
     * @param {'Number'} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update downloadable link of the given product (link type and its resources cannot be changed)
     * @param {String} sku 
     * @param {String} id 
     * @param {Object} opts Optional parameters
     * @param {module:model/Body79} opts.body 
     * @param {module:api/DownloadableLinkRepositoryV1Api~downloadableLinkRepositoryV1SavePutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link 'Number'}
     */
    this.downloadableLinkRepositoryV1SavePut = function(sku, id, opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];

      // verify the required parameter 'sku' is set
      if (sku === undefined || sku === null) {
        throw new Error("Missing the required parameter 'sku' when calling downloadableLinkRepositoryV1SavePut");
      }

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling downloadableLinkRepositoryV1SavePut");
      }


      var pathParams = {
        'sku': sku,
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = 'Number';

      return this.apiClient.callApi(
        '/V1/products/{sku}/downloadable-links/{id}', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
