/**
 * Magento Enterprise Edition 2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Body80', 'model/Body81', 'model/DownloadableDataSampleInterface', 'model/ErrorResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Body80'), require('../model/Body81'), require('../model/DownloadableDataSampleInterface'), require('../model/ErrorResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.magento) {
      root.magento = {};
    }
    root.magento.DownloadableSampleRepositoryV1Api = factory(root.magento.ApiClient, root.magento.Body80, root.magento.Body81, root.magento.DownloadableDataSampleInterface, root.magento.ErrorResponse);
  }
}(this, function(ApiClient, Body80, Body81, DownloadableDataSampleInterface, ErrorResponse) {
  'use strict';

  /**
   * DownloadableSampleRepositoryV1 service.
   * @module api/DownloadableSampleRepositoryV1Api
   * @version 2.0
   */

  /**
   * Constructs a new DownloadableSampleRepositoryV1Api. 
   * @alias module:api/DownloadableSampleRepositoryV1Api
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the downloadableSampleRepositoryV1DeleteDelete operation.
     * @callback module:api/DownloadableSampleRepositoryV1Api~downloadableSampleRepositoryV1DeleteDeleteCallback
     * @param {String} error Error message, if any.
     * @param {'Boolean'} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete downloadable sample
     * @param {Number} id 
     * @param {module:api/DownloadableSampleRepositoryV1Api~downloadableSampleRepositoryV1DeleteDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link 'Boolean'}
     */
    this.downloadableSampleRepositoryV1DeleteDelete = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling downloadableSampleRepositoryV1DeleteDelete");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = 'Boolean';

      return this.apiClient.callApi(
        '/V1/products/downloadable-links/samples/{id}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the downloadableSampleRepositoryV1GetListGet operation.
     * @callback module:api/DownloadableSampleRepositoryV1Api~downloadableSampleRepositoryV1GetListGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/DownloadableDataSampleInterface>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List of samples for downloadable product
     * @param {String} sku 
     * @param {module:api/DownloadableSampleRepositoryV1Api~downloadableSampleRepositoryV1GetListGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/DownloadableDataSampleInterface>}
     */
    this.downloadableSampleRepositoryV1GetListGet = function(sku, callback) {
      var postBody = null;

      // verify the required parameter 'sku' is set
      if (sku === undefined || sku === null) {
        throw new Error("Missing the required parameter 'sku' when calling downloadableSampleRepositoryV1GetListGet");
      }


      var pathParams = {
        'sku': sku
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = [DownloadableDataSampleInterface];

      return this.apiClient.callApi(
        '/V1/products/{sku}/downloadable-links/samples', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the downloadableSampleRepositoryV1SavePost operation.
     * @callback module:api/DownloadableSampleRepositoryV1Api~downloadableSampleRepositoryV1SavePostCallback
     * @param {String} error Error message, if any.
     * @param {'Number'} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update downloadable sample of the given product
     * @param {String} sku 
     * @param {Object} opts Optional parameters
     * @param {module:model/Body80} opts.body 
     * @param {module:api/DownloadableSampleRepositoryV1Api~downloadableSampleRepositoryV1SavePostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link 'Number'}
     */
    this.downloadableSampleRepositoryV1SavePost = function(sku, opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];

      // verify the required parameter 'sku' is set
      if (sku === undefined || sku === null) {
        throw new Error("Missing the required parameter 'sku' when calling downloadableSampleRepositoryV1SavePost");
      }


      var pathParams = {
        'sku': sku
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = 'Number';

      return this.apiClient.callApi(
        '/V1/products/{sku}/downloadable-links/samples', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the downloadableSampleRepositoryV1SavePut operation.
     * @callback module:api/DownloadableSampleRepositoryV1Api~downloadableSampleRepositoryV1SavePutCallback
     * @param {String} error Error message, if any.
     * @param {'Number'} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update downloadable sample of the given product
     * @param {String} sku 
     * @param {String} id 
     * @param {Object} opts Optional parameters
     * @param {module:model/Body81} opts.body 
     * @param {module:api/DownloadableSampleRepositoryV1Api~downloadableSampleRepositoryV1SavePutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link 'Number'}
     */
    this.downloadableSampleRepositoryV1SavePut = function(sku, id, opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];

      // verify the required parameter 'sku' is set
      if (sku === undefined || sku === null) {
        throw new Error("Missing the required parameter 'sku' when calling downloadableSampleRepositoryV1SavePut");
      }

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling downloadableSampleRepositoryV1SavePut");
      }


      var pathParams = {
        'sku': sku,
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = 'Number';

      return this.apiClient.callApi(
        '/V1/products/{sku}/downloadable-links/samples/{id}', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
