/**
 * Magento Enterprise Edition 2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Body70', 'model/ErrorResponse', 'model/SalesDataCreditmemoCommentInterface'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Body70'), require('../model/ErrorResponse'), require('../model/SalesDataCreditmemoCommentInterface'));
  } else {
    // Browser globals (root is window)
    if (!root.magento) {
      root.magento = {};
    }
    root.magento.SalesCreditmemoCommentRepositoryV1Api = factory(root.magento.ApiClient, root.magento.Body70, root.magento.ErrorResponse, root.magento.SalesDataCreditmemoCommentInterface);
  }
}(this, function(ApiClient, Body70, ErrorResponse, SalesDataCreditmemoCommentInterface) {
  'use strict';

  /**
   * SalesCreditmemoCommentRepositoryV1 service.
   * @module api/SalesCreditmemoCommentRepositoryV1Api
   * @version 2.0
   */

  /**
   * Constructs a new SalesCreditmemoCommentRepositoryV1Api. 
   * @alias module:api/SalesCreditmemoCommentRepositoryV1Api
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the salesCreditmemoCommentRepositoryV1SavePost operation.
     * @callback module:api/SalesCreditmemoCommentRepositoryV1Api~salesCreditmemoCommentRepositoryV1SavePostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SalesDataCreditmemoCommentInterface} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Performs persist operations for a specified entity.
     * @param {String} id 
     * @param {Object} opts Optional parameters
     * @param {module:model/Body70} opts.body 
     * @param {module:api/SalesCreditmemoCommentRepositoryV1Api~salesCreditmemoCommentRepositoryV1SavePostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SalesDataCreditmemoCommentInterface}
     */
    this.salesCreditmemoCommentRepositoryV1SavePost = function(id, opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling salesCreditmemoCommentRepositoryV1SavePost");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = SalesDataCreditmemoCommentInterface;

      return this.apiClient.callApi(
        '/V1/creditmemo/{id}/comments', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
