/**
 * Magento Enterprise Edition 2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Body93', 'model/Body94', 'model/ErrorResponse', 'model/TaxDataTaxRateInterface', 'model/TaxDataTaxRateSearchResultsInterface'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Body93'), require('../model/Body94'), require('../model/ErrorResponse'), require('../model/TaxDataTaxRateInterface'), require('../model/TaxDataTaxRateSearchResultsInterface'));
  } else {
    // Browser globals (root is window)
    if (!root.magento) {
      root.magento = {};
    }
    root.magento.TaxTaxRateRepositoryV1Api = factory(root.magento.ApiClient, root.magento.Body93, root.magento.Body94, root.magento.ErrorResponse, root.magento.TaxDataTaxRateInterface, root.magento.TaxDataTaxRateSearchResultsInterface);
  }
}(this, function(ApiClient, Body93, Body94, ErrorResponse, TaxDataTaxRateInterface, TaxDataTaxRateSearchResultsInterface) {
  'use strict';

  /**
   * TaxTaxRateRepositoryV1 service.
   * @module api/TaxTaxRateRepositoryV1Api
   * @version 2.0
   */

  /**
   * Constructs a new TaxTaxRateRepositoryV1Api. 
   * @alias module:api/TaxTaxRateRepositoryV1Api
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the taxTaxRateRepositoryV1DeleteByIdDelete operation.
     * @callback module:api/TaxTaxRateRepositoryV1Api~taxTaxRateRepositoryV1DeleteByIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param {'Boolean'} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete tax rate
     * @param {Number} rateId 
     * @param {module:api/TaxTaxRateRepositoryV1Api~taxTaxRateRepositoryV1DeleteByIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link 'Boolean'}
     */
    this.taxTaxRateRepositoryV1DeleteByIdDelete = function(rateId, callback) {
      var postBody = null;

      // verify the required parameter 'rateId' is set
      if (rateId === undefined || rateId === null) {
        throw new Error("Missing the required parameter 'rateId' when calling taxTaxRateRepositoryV1DeleteByIdDelete");
      }


      var pathParams = {
        'rateId': rateId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = 'Boolean';

      return this.apiClient.callApi(
        '/V1/taxRates/{rateId}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the taxTaxRateRepositoryV1GetGet operation.
     * @callback module:api/TaxTaxRateRepositoryV1Api~taxTaxRateRepositoryV1GetGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TaxDataTaxRateInterface} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get tax rate
     * @param {Number} rateId 
     * @param {module:api/TaxTaxRateRepositoryV1Api~taxTaxRateRepositoryV1GetGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TaxDataTaxRateInterface}
     */
    this.taxTaxRateRepositoryV1GetGet = function(rateId, callback) {
      var postBody = null;

      // verify the required parameter 'rateId' is set
      if (rateId === undefined || rateId === null) {
        throw new Error("Missing the required parameter 'rateId' when calling taxTaxRateRepositoryV1GetGet");
      }


      var pathParams = {
        'rateId': rateId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = TaxDataTaxRateInterface;

      return this.apiClient.callApi(
        '/V1/taxRates/{rateId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the taxTaxRateRepositoryV1GetListGet operation.
     * @callback module:api/TaxTaxRateRepositoryV1Api~taxTaxRateRepositoryV1GetListGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TaxDataTaxRateSearchResultsInterface} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Search TaxRates This call returns an array of objects, but detailed information about each object’s attributes might not be included. See http://devdocs.magento.com/codelinks/attributes.html#TaxRateRepositoryInterface to determine which call to use to get detailed information about all attributes for an object.
     * @param {Object} opts Optional parameters
     * @param {String} opts.searchCriteriaFilterGroupsFiltersField Field
     * @param {String} opts.searchCriteriaFilterGroupsFiltersValue Value
     * @param {String} opts.searchCriteriaFilterGroupsFiltersConditionType Condition type
     * @param {String} opts.searchCriteriaSortOrdersField Sorting field.
     * @param {String} opts.searchCriteriaSortOrdersDirection Sorting direction.
     * @param {Number} opts.searchCriteriaPageSize Page size.
     * @param {Number} opts.searchCriteriaCurrentPage Current page.
     * @param {module:api/TaxTaxRateRepositoryV1Api~taxTaxRateRepositoryV1GetListGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TaxDataTaxRateSearchResultsInterface}
     */
    this.taxTaxRateRepositoryV1GetListGet = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'searchCriteria[filterGroups][][filters][][field]': opts['searchCriteriaFilterGroupsFiltersField'],
        'searchCriteria[filterGroups][][filters][][value]': opts['searchCriteriaFilterGroupsFiltersValue'],
        'searchCriteria[filterGroups][][filters][][conditionType]': opts['searchCriteriaFilterGroupsFiltersConditionType'],
        'searchCriteria[sortOrders][][field]': opts['searchCriteriaSortOrdersField'],
        'searchCriteria[sortOrders][][direction]': opts['searchCriteriaSortOrdersDirection'],
        'searchCriteria[pageSize]': opts['searchCriteriaPageSize'],
        'searchCriteria[currentPage]': opts['searchCriteriaCurrentPage'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = TaxDataTaxRateSearchResultsInterface;

      return this.apiClient.callApi(
        '/V1/taxRates/search', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the taxTaxRateRepositoryV1SavePost operation.
     * @callback module:api/TaxTaxRateRepositoryV1Api~taxTaxRateRepositoryV1SavePostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TaxDataTaxRateInterface} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create or update tax rate
     * @param {Object} opts Optional parameters
     * @param {module:model/Body94} opts.body 
     * @param {module:api/TaxTaxRateRepositoryV1Api~taxTaxRateRepositoryV1SavePostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TaxDataTaxRateInterface}
     */
    this.taxTaxRateRepositoryV1SavePost = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = TaxDataTaxRateInterface;

      return this.apiClient.callApi(
        '/V1/taxRates', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the taxTaxRateRepositoryV1SavePut operation.
     * @callback module:api/TaxTaxRateRepositoryV1Api~taxTaxRateRepositoryV1SavePutCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TaxDataTaxRateInterface} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create or update tax rate
     * @param {Object} opts Optional parameters
     * @param {module:model/Body93} opts.body 
     * @param {module:api/TaxTaxRateRepositoryV1Api~taxTaxRateRepositoryV1SavePutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TaxDataTaxRateInterface}
     */
    this.taxTaxRateRepositoryV1SavePut = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = TaxDataTaxRateInterface;

      return this.apiClient.callApi(
        '/V1/taxRates', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
