/**
 * Magento Enterprise Edition 2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.magento);
  }
}(this, function(expect, magento) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new magento.DirectoryDataCurrencyInformationInterface();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DirectoryDataCurrencyInformationInterface', function() {
    it('should create an instance of DirectoryDataCurrencyInformationInterface', function() {
      // uncomment below and update the code to test DirectoryDataCurrencyInformationInterface
      //var instane = new magento.DirectoryDataCurrencyInformationInterface();
      //expect(instance).to.be.a(magento.DirectoryDataCurrencyInformationInterface);
    });

    it('should have the property baseCurrencyCode (base name: "baseCurrencyCode")', function() {
      // uncomment below and update the code to test the property baseCurrencyCode
      //var instane = new magento.DirectoryDataCurrencyInformationInterface();
      //expect(instance).to.be();
    });

    it('should have the property baseCurrencySymbol (base name: "baseCurrencySymbol")', function() {
      // uncomment below and update the code to test the property baseCurrencySymbol
      //var instane = new magento.DirectoryDataCurrencyInformationInterface();
      //expect(instance).to.be();
    });

    it('should have the property defaultDisplayCurrencyCode (base name: "defaultDisplayCurrencyCode")', function() {
      // uncomment below and update the code to test the property defaultDisplayCurrencyCode
      //var instane = new magento.DirectoryDataCurrencyInformationInterface();
      //expect(instance).to.be();
    });

    it('should have the property defaultDisplayCurrencySymbol (base name: "defaultDisplayCurrencySymbol")', function() {
      // uncomment below and update the code to test the property defaultDisplayCurrencySymbol
      //var instane = new magento.DirectoryDataCurrencyInformationInterface();
      //expect(instance).to.be();
    });

    it('should have the property availableCurrencyCodes (base name: "availableCurrencyCodes")', function() {
      // uncomment below and update the code to test the property availableCurrencyCodes
      //var instane = new magento.DirectoryDataCurrencyInformationInterface();
      //expect(instance).to.be();
    });

    it('should have the property exchangeRates (base name: "exchangeRates")', function() {
      // uncomment below and update the code to test the property exchangeRates
      //var instane = new magento.DirectoryDataCurrencyInformationInterface();
      //expect(instance).to.be();
    });

    it('should have the property extensionAttributes (base name: "extensionAttributes")', function() {
      // uncomment below and update the code to test the property extensionAttributes
      //var instane = new magento.DirectoryDataCurrencyInformationInterface();
      //expect(instance).to.be();
    });

  });

}));
