/**
 * Magento Enterprise Edition 2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.magento);
  }
}(this, function(expect, magento) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new magento.FrameworkDataVideoContentInterface();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FrameworkDataVideoContentInterface', function() {
    it('should create an instance of FrameworkDataVideoContentInterface', function() {
      // uncomment below and update the code to test FrameworkDataVideoContentInterface
      //var instane = new magento.FrameworkDataVideoContentInterface();
      //expect(instance).to.be.a(magento.FrameworkDataVideoContentInterface);
    });

    it('should have the property mediaType (base name: "mediaType")', function() {
      // uncomment below and update the code to test the property mediaType
      //var instane = new magento.FrameworkDataVideoContentInterface();
      //expect(instance).to.be();
    });

    it('should have the property videoProvider (base name: "videoProvider")', function() {
      // uncomment below and update the code to test the property videoProvider
      //var instane = new magento.FrameworkDataVideoContentInterface();
      //expect(instance).to.be();
    });

    it('should have the property videoUrl (base name: "videoUrl")', function() {
      // uncomment below and update the code to test the property videoUrl
      //var instane = new magento.FrameworkDataVideoContentInterface();
      //expect(instance).to.be();
    });

    it('should have the property videoTitle (base name: "videoTitle")', function() {
      // uncomment below and update the code to test the property videoTitle
      //var instane = new magento.FrameworkDataVideoContentInterface();
      //expect(instance).to.be();
    });

    it('should have the property videoDescription (base name: "videoDescription")', function() {
      // uncomment below and update the code to test the property videoDescription
      //var instane = new magento.FrameworkDataVideoContentInterface();
      //expect(instance).to.be();
    });

    it('should have the property videoMetadata (base name: "videoMetadata")', function() {
      // uncomment below and update the code to test the property videoMetadata
      //var instane = new magento.FrameworkDataVideoContentInterface();
      //expect(instance).to.be();
    });

  });

}));
