/**
 * Magento Enterprise Edition 2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.magento);
  }
}(this, function(expect, magento) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new magento.SalesRuleDataCouponGenerationSpecInterface();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SalesRuleDataCouponGenerationSpecInterface', function() {
    it('should create an instance of SalesRuleDataCouponGenerationSpecInterface', function() {
      // uncomment below and update the code to test SalesRuleDataCouponGenerationSpecInterface
      //var instane = new magento.SalesRuleDataCouponGenerationSpecInterface();
      //expect(instance).to.be.a(magento.SalesRuleDataCouponGenerationSpecInterface);
    });

    it('should have the property ruleId (base name: "ruleId")', function() {
      // uncomment below and update the code to test the property ruleId
      //var instane = new magento.SalesRuleDataCouponGenerationSpecInterface();
      //expect(instance).to.be();
    });

    it('should have the property format (base name: "format")', function() {
      // uncomment below and update the code to test the property format
      //var instane = new magento.SalesRuleDataCouponGenerationSpecInterface();
      //expect(instance).to.be();
    });

    it('should have the property quantity (base name: "quantity")', function() {
      // uncomment below and update the code to test the property quantity
      //var instane = new magento.SalesRuleDataCouponGenerationSpecInterface();
      //expect(instance).to.be();
    });

    it('should have the property length (base name: "length")', function() {
      // uncomment below and update the code to test the property length
      //var instane = new magento.SalesRuleDataCouponGenerationSpecInterface();
      //expect(instance).to.be();
    });

    it('should have the property prefix (base name: "prefix")', function() {
      // uncomment below and update the code to test the property prefix
      //var instane = new magento.SalesRuleDataCouponGenerationSpecInterface();
      //expect(instance).to.be();
    });

    it('should have the property suffix (base name: "suffix")', function() {
      // uncomment below and update the code to test the property suffix
      //var instane = new magento.SalesRuleDataCouponGenerationSpecInterface();
      //expect(instance).to.be();
    });

    it('should have the property delimiterAtEvery (base name: "delimiterAtEvery")', function() {
      // uncomment below and update the code to test the property delimiterAtEvery
      //var instane = new magento.SalesRuleDataCouponGenerationSpecInterface();
      //expect(instance).to.be();
    });

    it('should have the property delimiter (base name: "delimiter")', function() {
      // uncomment below and update the code to test the property delimiter
      //var instane = new magento.SalesRuleDataCouponGenerationSpecInterface();
      //expect(instance).to.be();
    });

    it('should have the property extensionAttributes (base name: "extensionAttributes")', function() {
      // uncomment below and update the code to test the property extensionAttributes
      //var instane = new magento.SalesRuleDataCouponGenerationSpecInterface();
      //expect(instance).to.be();
    });

  });

}));
